export const PROFILE = {
  nom: "Mehdi Ahmiddouch",
  age: 18,
  formation: "BTS SIO option SISR",
  ecole: "H3 Campus",
  tagline: "Etudiant en BTS SIO SISR, passionne par l'administration systemes, reseaux et la cybersecurite.",
  objectif: "Devenir administrateur systemes et reseaux, avec une specialisation en cybersecurite.",
  phone: "07 67 09 34 20",
  cv: "/assets/CV_Mehdi_Amd.pdf",

  presentation: {
    texte: "Je suis Mehdi Ahmiddouch, 18 ans, etudiant en BTS SIO specialite SISR. Curieux, motive et passionne par la cybersecurite, j'explore les domaines du reseau, de la virtualisation et de l'automatisation pour batir des systemes solides et efficaces. Mon objectif : evoluer dans un environnement ou la securite informatique et l'innovation technique vont de pair.",
    points: [
      "Passionne par la cybersecurite et les infrastructures reseau",
      "Curieux et autonome dans l'apprentissage de nouvelles technologies",
      "Rigoureux dans la mise en place et la documentation de projets",
      "A l'aise aussi bien en environnement Linux qu'en Windows Server",
    ],
  },

  ecoles: [
    {
      nom: "H3 Campus - IPSSI SQY",
      logo: "/assets/logo-h3campus.webp",
      periode: "Septembre 2025 - Juin 2026",
      diplome: "BTS SIO option SISR - 2eme annee",
      lieu: "Saint-Quentin-en-Yvelines",
      description: "H3 Campus est une grande ecole d'informatique. En 2eme annee de BTS SIO SISR, j'approfondis mes competences en administration systemes, reseaux, cybersecurite et gestion de parc, en alternance chez ATERMES.",
      matieres: ["Administration systemes", "Reseaux & securite", "Cybersecurite", "Gestion de parc", "Anglais technique"],
      couleur: "from-sky-600 to-blue-700",
      futur: false,
    },
    {
      nom: "IPSSI SQY",
      logo: "/assets/logo-h3campus.webp",
      periode: "Septembre 2024 - Juin 2025",
      diplome: "BTS SIO option SISR - 1ere annee",
      lieu: "Saint-Quentin-en-Yvelines",
      description: "L'IPSSI est une grande ecole d'informatique specialisee dans les metiers de la securite et des systemes d'information. En 1ere annee, j'ai acquis les bases solides en administration systemes, reseaux et securite informatique.",
      matieres: ["Linux & Windows Server", "Reseaux TCP/IP", "Virtualisation", "Securite informatique", "Projets AP1"],
      couleur: "from-violet-600 to-purple-700",
      futur: false,
    },
    {
      nom: "IUT de Velizy-Rambouillet - UVSQ",
      logo: "/assets/logo-uvsq.jpg",
      periode: "Septembre 2026 - Juin 2027 (visee)",
      diplome: "Licence Pro MRIT parcours ASUR - Cybersecurite",
      lieu: "Velizy-Villacoublay (78)",
      description: "Mon projet de poursuite d'etudes apres le BTS SIO SISR. La Licence Pro MRIT parcours ASUR me permettra de me specialiser en cybersecurite et administration reseau.",
      matieres: ["Cybersecurite", "Administration reseaux", "Telecommunications", "Securite des SI", "Formation en ligne"],
      infos: [
        { label: "Niveau requis", value: "Bac +2" },
        { label: "Duree", value: "2 semestres - 60 ECTS" },
        { label: "Site", value: "Velizy" },
        { label: "Discipline", value: "Informatique & Reseaux telecom" },
      ],
      couleur: "from-amber-500 to-orange-500",
      futur: true,
    },
  ],

  entreprises: [
    {
      nom: "ATERMES",
      logo: "/assets/logo-atermes.png",
      type: "Alternance",
      periode: "Septembre 2025 - Juin 2026",
      lieu: "Yvelines",
      description: "La Societe ATERMES, creee en 1989, est devenue un groupe compose de plus de 150 personnes. ATERMES a developpe des competences sur ses quatre metiers cles : Mecanique, Electronique, Optronique et Logiciel.",
      missions: [
        "Administration systemes et reseaux",
        "Mise en place de services informatiques",
        "Support technique et maintenance",
        "Participation aux projets d'infrastructure",
      ],
      secteur: "Industrie de defense & haute technologie",
      effectif: "+150 personnes",
      fondation: "1989",
      couleur: "from-red-700 to-rose-800",
    },
    {
      nom: "Mairie de Coignieres",
      logo: "/assets/logo-coignieres.jpg",
      type: "Stage",
      periode: "28 avril - 25 juin 2025 (8 semaines)",
      lieu: "Coignieres, Yvelines (78)",
      description: "Stage de 8 semaines au sein de la DSI de la Mairie de Coignieres. J'ai participe a l'administration du parc informatique, la supervision reseau et le support aux agents municipaux.",
      missions: [
        "Installation et configuration d'un serveur HP ProLiant sous Debian 12",
        "Deploiement de Zabbix 6.0 pour la supervision reseau",
        "Analyse et schematisation de l'infrastructure reseau",
        "Support technique des agents municipaux",
        "Deplacements dans les ecoles, CCAS et MDJ pour resoudre incidents reseau, VPN et materiel",
        "Creation de comptes utilisateurs (GLPI, messagerie pro)",
      ],
      secteur: "Collectivite territoriale",
      effectif: "Service DSI",
      couleur: "from-emerald-600 to-teal-700",
    },
  ],

  apropos: {
    parcours: [
      { titre: "BTS SIO option SISR - 2eme annee", ecole: "H3 Campus", periode: "Sept. 2025 - Juin 2026" },
      { titre: "BTS SIO option SISR - 1ere annee", ecole: "IPSSI SQY", periode: "Sept. 2024 - Juin 2025" },
      { titre: "Baccalaureat Technologique", ecole: "Lycee La Plaine de Neauphle", periode: "Sept. 2023 - Aout 2024" },
      { titre: "Brevet des Colleges", ecole: "Gustave Courbet", periode: "Juin 2021 - Mention AB" },
    ],
  },

  competences: [
    { categorie: "Systemes", icon: "PC", items: ["Debian 12", "Ubuntu 22.04", "Administration Linux", "VirtualBox", "Gestion utilisateurs", "XAMPP", "Windows Server"] },
    { categorie: "Reseaux", icon: "NET", items: ["Configuration reseau", "VPN", "Cisco Packet Tracer", "Schemas reseau", "VLANs", "802.1Q"] },
    { categorie: "Securite", icon: "SEC", items: ["SSH securise", "Kali Linux", "Etude du 2FA", "Antivirus", "WPA2-PSK", "TLS/SSL"] },
    { categorie: "Supervision", icon: "MON", items: ["Zabbix 6.0", "Monitoring CPU/RAM", "Tableaux de bord", "Alertes reseau"] },
    { categorie: "Gestion de parc", icon: "PAR", items: ["GLPI", "OCS Inventory", "GPO Windows Server", "FileZilla FTPS", "Active Directory"] },
    { categorie: "Outils & Dev", icon: "OTL", items: ["Pack Microsoft Office", "Trello", "Canva", "Figma", "HTML/CSS/JS"] },
  ],

  langues: [
    { langue: "Anglais", niveau: "Intermediaire", stars: 3 },
    { langue: "Allemand", niveau: "Notions", stars: 2 },
  ],

  contact: {
    email: "mehdiahmiddouch78@gmail.com",
    linkedin: "https://www.linkedin.com/in/mehdi-ahmiddouch-bb491b341/",
    github: "https://github.com/mehdi7881",
    localisation: "Trappes, Ile-de-France",
    phone: "07 67 09 34 20",
  },
};

export const PROJETS = [
  {
    id: "zabbix-supervision",
    titre: "Infrastructure Debian + Supervision Zabbix",
    courte: "Serveur HP ProLiant Debian 12 avec monitoring reseau Zabbix",
    description: "Durant mon stage de 8 semaines a la Mairie de Coignieres, j'ai installe et configure un serveur HP ProLiant sous Debian 12, puis deploye Zabbix 6.0 pour assurer la supervision du reseau et des hotes Windows.",
    contexte: "Besoin de superviser l'infrastructure informatique de la mairie en temps reel.",
    objectif: "Mettre en place une solution de monitoring centralisee pour surveiller les serveurs et postes du reseau.",
    resultat: "Tableau de bord Zabbix operationnel avec alertes CPU, RAM et espace disque configurees.",
    technologies: ["Debian 12", "Zabbix 6.0", "Linux", "MariaDB", "Apache2", "Windows Server"],
    categorie: "Infrastructure",
    type: "entreprise",
    missions: [
      "Installation de Debian 12 sur serveur HP ProLiant",
      "Configuration reseau et services systeme (MariaDB, Apache2)",
      "Deploiement de Zabbix 6.0 (serveur + agents)",
      "Ajout d'hotes Windows dans l'interface Zabbix",
      "Creation de tableaux de bord de supervision",
      "Configuration des alertes (CPU > 90%, espace disque)",
      "Documentation technique de l'installation",
    ],
    images: [
      { src: "/assets/debian-server.JPG", legende: "Serveur Debian 12 + interface Zabbix en production" },
      { src: "/assets/zabbix_dashboard.png", legende: "Tableau de bord Zabbix - supervision CPU et espace disque" },
      { src: "/assets/zabbix-install.png", legende: "Installation reussie de l'interface Zabbix" },
    ],
    documents: [
      { nom: "Documentation Zabbix", fichier: "/assets/Documentation_zabbix.pdf", description: "Guide d'installation et configuration de l'agent Zabbix" },
    ],
    couleur: "from-blue-600 to-cyan-500",
    icon: "MON",
  },
  {
    id: "infrastructure-reseau",
    titre: "Infrastructure Reseau Mairie de Coignieres",
    courte: "Analyse et schematisation de l'infrastructure reseau de la mairie",
    description: "Analyse complete de l'infrastructure reseau de la Mairie de Coignieres. Realisation de schemas de topologie reseau incluant la segmentation par VLANs et la configuration des points d'acces Wi-Fi.",
    contexte: "Besoin de documenter et cartographier l'infrastructure reseau existante de la mairie.",
    objectif: "Produire une documentation reseau complete et des schemas de topologie a jour.",
    resultat: "Documentation reseau complete avec schemas VLANs et inventaire des equipements actifs.",
    technologies: ["Cisco Packet Tracer", "VLANs", "WPA2-PSK", "Documentation reseau"],
    categorie: "Reseau",
    type: "entreprise",
    missions: [
      "Audit de l'infrastructure reseau existante",
      "Realisation du schema de topologie reseau",
      "Documentation des VLANs (Admin, Guests, Organisation)",
      "Analyse des points d'acces Wi-Fi et niveaux de securite",
      "Identification des equipements actifs (commutateurs, routeurs)",
      "Redaction de la documentation technique",
    ],
    images: [
      { src: "/assets/inframairie.png", legende: "Schema d'infrastructure reseau de la Mairie de Coignieres - VLANs, switches, pare-feu, videosurveillance" },
    ],
    documents: [],
    couleur: "from-emerald-600 to-teal-500",
    icon: "NET",
  },
  {
    id: "gestion-parc",
    titre: "Deploiement OCS Inventory + GLPI + GPO",
    courte: "Solution complete de gestion de parc avec inventaire automatise via GPO",
    description: "Mise en place d'une solution complete de gestion de parc informatique avec GLPI et OCS Inventory. Deploiement automatise des agents OCS via GPO sur les postes Windows du domaine.",
    contexte: "Besoin de centraliser l'inventaire du parc et le suivi des equipements.",
    objectif: "Mettre en place une solution inventaire + gestion de parc et automatiser le deploiement de l'agent sur les postes.",
    resultat: "Inventaire automatise et centralise, parc visible dans GLPI, deploiement agent industrialise via GPO.",
    technologies: ["GLPI", "OCS Inventory", "Windows Server", "GPO", "Active Directory"],
    categorie: "Gestion de parc",
    type: "entreprise",
    missions: [
      "Installation et configuration de GLPI",
      "Deploiement d'OCS Inventory Server",
      "Liaison GLPI - OCS pour synchronisation automatique",
      "Preparation du package agent OCS",
      "Deploiement de l'agent via GPO sur les postes du domaine",
      "Verification de la remontee des machines",
    ],
    images: [],
    documents: [],
    couleur: "from-amber-600 to-yellow-500",
    icon: "PAR",
  },
  {
    id: "virtualisation",
    titre: "Mise en place d'un serveur FTPS (FileZilla)",
    courte: "Serveur FTP securise en FTPS pour echanges internes/externes",
    description: "Mise en place d'un serveur FileZilla en mode FTPS (FTP over TLS/SSL) pour le transfert securise de fichiers.",
    contexte: "Besoin de mettre a disposition un partage de fichiers securise pour des echanges internes/externes.",
    objectif: "Deployer un serveur FTP securise en FTPS afin de chiffrer les transferts et renforcer la confidentialite.",
    resultat: "Service operationnel : transferts chiffres, acces controle par comptes et permissions.",
    technologies: ["VirtualBox", "FileZilla Server", "FTPS", "TLS/SSL", "Windows Server"],
    categorie: "Infrastructure",
    type: "entreprise",
    missions: [
      "Installation de FileZilla Server sur VM Windows Server",
      "Activation du FTPS (TLS)",
      "Parametrage reseau (ports / acces)",
      "Tests de connexion securisee",
      "Creation de comptes et droits d'acces",
      "Documentation de la procedure",
    ],
    images: [],
    documents: [],
    couleur: "from-sky-600 to-indigo-500",
    icon: "SRV",
  },
  {
    id: "ap2-m2l",
    titre: "AP2 - Projets DYLAN & ASSIZ (Maison des Ligues)",
    courte: "Insertion dynamique VLAN et infrastructure Wi-Fi temporaire pour la M2L",
    description: "Atelier de Professionnalisation N2 realise en groupe (Ali H., Sasha H., Mehdi A.) dans le contexte de la Maison des Ligues (M2L). Deux missions : le projet DYLAN (insertion dynamique des PC portables dans le bon VLAN via MAC-based VLAN) et le projet ASSIZ (infrastructure Wi-Fi temporaire securisee pour les VIemes assises nationales de l'Escrime).",
    contexte: "La Maison des Ligues heberge plusieurs organisations sportives partageant un reseau commun.",
    objectif: "Mission 1 : insertion dynamique des PC dans le bon VLAN. Mission 2 : infrastructure Wi-Fi temporaire securisee.",
    resultat: "Solution MAC-based VLAN retenue pour DYLAN. Infrastructure Wi-Fi a 3 points d'acces segmentes retenue pour ASSIZ.",
    technologies: ["Cisco Packet Tracer", "MAC-based VLAN", "802.1Q", "Wi-Fi", "WPA2-PSK", "SSID", "Switch Cisco"],
    categorie: "Reseau",
    type: "scolaire",
    missions: [
      "Analyse du contexte de la Maison des Ligues",
      "Etude et comparaison de 3 solutions VLAN (Port-based, Protocol-based, MAC-based)",
      "Choix et justification de la solution MAC-based VLAN pour DYLAN",
      "Conception de l'infrastructure Wi-Fi temporaire pour ASSIZ",
      "Etude de 2 solutions Wi-Fi (SSID multiples vs Controleur + VLANs)",
      "Maquettage sur Cisco Packet Tracer",
      "Redaction du dossier AP2 et presentation PowerPoint",
    ],
    images: [
      { src: "/assets/dylan.png", legende: "Projet DYLAN - Topologie reseau MAC-based VLAN sur Cisco Packet Tracer" },
      { src: "/assets/assiz.png", legende: "Projet ASSIZ - Infrastructure Wi-Fi temporaire avec segmentation VLANs" },
    ],
    documents: [
      { nom: "Dossier AP2 - Rapport complet", fichier: "/assets/AP2_M2L.docx", description: "Rapport Word complet : contexte, solutions, comparaison, annexes" },
      { nom: "Presentation AP2 - PowerPoint", fichier: "/assets/AP2_presentation.pptx", description: "Support de presentation du projet devant le jury" },
    ],
    couleur: "from-blue-600 to-indigo-500",
    icon: "ENT",
  },
  {
    id: "projet-dylan",
    titre: "Projet DYLAN - Insertion dynamique VLAN",
    courte: "Insertion dynamique des PC portables dans leur VLAN a la Maison des Ligues",
    description: "Ce projet vise a permettre l'insertion dynamique des PC portables dans le VLAN correspondant a leur structure lorsqu'ils sont connectes a une prise Ethernet commune dans les salles de reunion de la Maison des Ligues (M2L).",
    contexte: "La Maison des Ligues accueille plusieurs structures qui partagent des prises reseau communes.",
    objectif: "Configurer une infrastructure reseau permettant l'insertion dynamique des equipements dans le bon VLAN.",
    resultat: "Infrastructure reseau fonctionnelle avec affectation automatique des VLANs par structure.",
    technologies: ["Cisco Packet Tracer", "VLANs", "802.1Q", "Switches Cisco"],
    categorie: "Reseau",
    type: "scolaire",
    missions: [
      "Analyse du besoin et de l'infrastructure existante",
      "Conception de la topologie reseau avec VLANs",
      "Configuration des switches Cisco",
      "Mise en place du 802.1Q (trunk)",
      "Tests de connectivite entre VLANs",
      "Documentation et schema reseau",
    ],
    images: [
      { src: "/assets/dylan.png", legende: "Schema reseau du projet DYLAN - topologie Cisco Packet Tracer" },
    ],
    documents: [],
    couleur: "from-blue-600 to-indigo-500",
    icon: "VLN",
  },
  {
    id: "projet-assiz",
    titre: "Projet ASSIZ - Infrastructure Wi-Fi Escrime",
    courte: "Infrastructure Wi-Fi temporaire securisee pour les VIemes assises nationales de l'Escrime",
    description: "Projet visant a concevoir et deployer une infrastructure Wi-Fi temporaire pour les VIemes assises nationales de l'Escrime. La mission : creer un reseau Wi-Fi temporaire bien securise, avec des acces separes pour les invites et le staff.",
    contexte: "Les assises nationales de l'Escrime necessitent un reseau Wi-Fi temporaire securise avec separation des acces.",
    objectif: "Deployer une infrastructure Wi-Fi temporaire avec segmentation invites/staff et securisation des acces.",
    resultat: "Infrastructure Wi-Fi operationnelle avec VLANs separes et WPA2-PSK pour le staff.",
    technologies: ["Wi-Fi", "VLANs", "WPA2-PSK", "Cisco Packet Tracer", "Points d'acces"],
    categorie: "Reseau",
    type: "scolaire",
    missions: [
      "Analyse des besoins en connectivite",
      "Conception de l'architecture Wi-Fi temporaire",
      "Configuration des points d'acces (SSID staff / invites)",
      "Segmentation reseau avec VLANs",
      "Securisation WPA2-PSK pour le staff",
      "Tests et validation de l'infrastructure",
    ],
    images: [
      { src: "/assets/assiz.png", legende: "Schema reseau Wi-Fi temporaire - Projet ASSIZ" },
    ],
    documents: [],
    couleur: "from-emerald-600 to-green-500",
    icon: "WIF",
  },
  {
    id: "cybersecurite-linux",
    titre: "Cybersecurite & Linux",
    courte: "Etude du 2FA, VM Kali Linux et acces SSH securise",
    description: "Etude des mecanismes d'authentification a deux facteurs (2FA) et de leurs vulnerabilites, configuration d'une machine virtuelle Kali Linux pour des tests de penetration, et mise en place d'un acces SSH securise avec cles asymetriques.",
    contexte: "TP de securite informatique a l'IPSSI - comprendre les attaques et les defenses.",
    objectif: "Comprendre le contournement du 2FA et securiser un acces distant via SSH.",
    resultat: "Maitrise des techniques d'attaque 2FA et d'un acces SSH securise par cles RSA.",
    technologies: ["Kali Linux", "SSH", "VirtualBox", "2FA", "RSA"],
    categorie: "Securite",
    type: "scolaire",
    missions: [
      "Configuration d'une VM Kali Linux sous VirtualBox",
      "Etude du contournement de l'authentification 2FA",
      "Mise en place d'un acces SSH avec cles RSA",
      "Tests de securite en environnement isole",
      "Analyse des vulnerabilites d'authentification",
      "Redaction d'un rapport de securite",
    ],
    images: [
      { src: "/assets/hacked.png", legende: "Environnement de test cybersecurite" },
    ],
    documents: [],
    couleur: "from-red-600 to-orange-500",
    icon: "SEC",
  },
  {
    id: "site-web",
    titre: "Developpement Web - Site Vitrine",
    courte: "Site web HTML/CSS/JS avec charte graphique Figma",
    description: "Dans le cadre du projet AP1 a l'IPSSI, creation d'un site vitrine complet en HTML, CSS et JavaScript. Conception de la charte graphique avec Figma, creation des visuels et integration de l'ensemble des contenus.",
    contexte: "Projet AP1 IPSSI - creation d'une entreprise fictive avec presence web.",
    objectif: "Creer un site vitrine complet avec charte graphique professionnelle.",
    resultat: "Site web operationnel avec design coherent et contenu complet.",
    technologies: ["HTML", "CSS", "JavaScript", "Figma", "Canva"],
    categorie: "Developpement",
    type: "scolaire",
    missions: [
      "Conception de la maquette sur Figma",
      "Creation de la charte graphique",
      "Developpement du site en HTML/CSS/JS",
      "Creation des bannieres et elements graphiques",
      "Integration du contenu (produits, services)",
      "Optimisation responsive",
    ],
    images: [
      { src: "/assets/githubVrai.png", legende: "Apercu du projet sur GitHub" },
    ],
    documents: [],
    couleur: "from-violet-600 to-purple-500",
    icon: "WEB",
  },
];

export const VEILLE = [
  {
    titre: "Ransomware as a Service : NightSpire, nouveau groupe RaaS",
    date: "Avril 2026",
    resume: "Apparue debut 2025, l'enseigne de ransomware NightSpire s'est presentee sous les apparences d'une operation fermee avant de manifester des signes d'ouverture a un modele RaaS. Une nouvelle menace qui cible entreprises et collectivites.",
    source: "LeMagIT",
    image: "/assets/ransomware.webp",
    lien: "https://www.lemagit.fr/actualites/366641805/Cyberhebdo-du-17-avril-2026",
    projetId: "cybersecurite-linux",
  },
  {
    titre: "ANSSI - Panorama de la cybermenace 2025",
    date: "Mars 2026",
    resume: "L'ANSSI a publie le 11 mars 2026 son Panorama de la cybermenace 2025. En France, les cyberattaques ont progresse de 38% en un an. 43% des collectivites territoriales ont subi au moins une tentative de ransomware en 2025.",
    source: "ANSSI",
    image: "/assets/hacked.png",
    lien: "https://cyber.gouv.fr/",
    projetId: "cybersecurite-linux",
  },
  {
    titre: "NIS 2 : l'ANSSI deploie ReCyF et impose la conformite",
    date: "Mars 2026",
    resume: "Depuis le 17 mars 2026, l'ANSSI met a disposition le Referentiel Cyber France (ReCyF) pour atteindre les objectifs de securite fixes par la directive NIS 2. Un calendrier de conformite avec des jalons et niveaux de maturite attendus.",
    source: "ANSSI / IT-Connect",
    image: "/assets/hacked.png",
    lien: "https://www.it-connect.fr/securite-de-etat-lanssi-devoile-sa-feuille-de-route-pour-2026-2027/",
    projetId: "cybersecurite-linux",
  },
  {
    titre: "Cybersecurite 2026 : l'IA au service des attaquants",
    date: "Janvier 2026",
    resume: "Les pirates utilisent l'IA generative et les deepfakes pour lancer des attaques de phishing a grande echelle. 91% des cyberattaques reussies debutent par un email frauduleux selon le rapport ANSSI 2025.",
    source: "LeMagIT",
    image: "/assets/ransomware.webp",
    lien: "https://www.lemagit.fr/actualites/366637562/Les-8-principales-previsions-en-matiere-de-cybersecurite-pour-2026",
    projetId: "cybersecurite-linux",
  },
  {
    titre: "Contournement du 2FA : techniques d'attaque 2024-2025",
    date: "2024 - 2025",
    resume: "Etude des mecanismes d'authentification a deux facteurs et de leurs vulnerabilites : attaques par phishing de session (evilginx), SIM swapping, et contournement via API.",
    source: "Travaux pratiques IPSSI",
    image: "/assets/hacked.png",
    lien: null,
    projetId: "cybersecurite-linux",
  },
  {
    titre: "Menaces sur le stockage : ransomware et IA en 2026",
    date: "Decembre 2025",
    resume: "Les attaques par ransomware utilisant l'IA font partie des principales preoccupations pour 2026. Les pirates utilisent l'IA pour rechercher les vulnerabilites des systemes de stockage et lancer des attaques automatisees.",
    source: "LeMagIT",
    image: "/assets/ransomware.webp",
    lien: "https://www.lemagit.fr/conseil/Cybersecurite-ces-menaces-qui-vont-peser-sur-le-stockage-de-donnees-en-2026",
    projetId: "cybersecurite-linux",
  },
];
