// ─── DONNÉES CENTRALISÉES ────────────────────────────────────────────────────

export const PROFILE = {
  nom: "Mehdi Ahmiddouch",
  age: 18,
  formation: "BTS SIO option SISR",
  ecole: "H3 Campus",
  tagline: "Étudiant en BTS SIO SISR, passionné par l'administration systèmes, réseaux et la cybersécurité.",
  objectif: "Devenir administrateur systèmes et réseaux, avec une spécialisation en cybersécurité.",
  phone: "07 67 09 34 20",
  cv: "/assets/CV_Mehdi_Amd.pdf",

  presentation: {
    texte: "Je suis Mehdi Ahmiddouch, 18 ans, étudiant en BTS SIO spécialité SISR. Curieux, motivé et passionné par la cybersécurité, j'explore les domaines du réseau, de la virtualisation et de l'automatisation pour bâtir des systèmes solides et efficaces. Mon objectif : évoluer dans un environnement où la sécurité informatique et l'innovation technique vont de pair.",
    points: [
      "Passionné par la cybersécurité et les infrastructures réseau",
      "Curieux et autonome dans l'apprentissage de nouvelles technologies",
      "Rigoureux dans la mise en place et la documentation de projets",
      "À l'aise aussi bien en environnement Linux qu'en Windows Server",
    ],
  },

  ecoles: [
    {
      nom: "H3 Campus — IPSSI SQY",
      logo: null,
      periode: "Septembre 2025 – Juin 2026",
      diplome: "BTS SIO option SISR — 2ème année",
      lieu: "Saint-Quentin-en-Yvelines",
      description: "H3 Campus est une grande école d'informatique. En 2ème année de BTS SIO SISR, j'approfondis mes compétences en administration systèmes, réseaux, cybersécurité et gestion de parc, en alternance chez ATERMES.",
      matieres: ["Administration systèmes", "Réseaux & sécurité", "Cybersécurité", "Gestion de parc", "Anglais technique"],
      couleur: "from-sky-600 to-blue-700",
      futur: false,
    },
    {
      nom: "IPSSI SQY",
      logo: null,
      periode: "Septembre 2024 – Juin 2025",
      diplome: "BTS SIO option SISR — 1ère année",
      lieu: "Saint-Quentin-en-Yvelines",
      description: "L'IPSSI (Institut Privé des Sciences et de la Sécurité Informatique) est une grande école d'informatique spécialisée dans les métiers de la sécurité et des systèmes d'information. En 1ère année, j'ai acquis les bases solides en administration systèmes, réseaux et sécurité informatique.",
      matieres: ["Linux & Windows Server", "Réseaux TCP/IP", "Virtualisation", "Sécurité informatique", "Projets AP1"],
      couleur: "from-violet-600 to-purple-700",
      futur: false,
    },
    {
      nom: "IUT de Vélizy-Rambouillet — UVSQ",
      logo: null,
      periode: "Septembre 2026 – Juin 2027 (visée)",
      diplome: "Licence Pro MRIT parcours ASUR — Cybersécurité",
      lieu: "Vélizy-Villacoublay (78)",
      description: "Mon projet de poursuite d'études après le BTS SIO SISR. La Licence Professionnelle Mention Métiers des Réseaux Informatiques et des Télécommunications, parcours Administration et Sécurité des Réseaux (ASUR), me permettra de me spécialiser en cybersécurité et d'approfondir mes compétences en administration réseau.",
      matieres: ["Cybersécurité", "Administration réseaux", "Télécommunications", "Sécurité des SI", "Formation en ligne"],
      infos: [
        { label: "Niveau requis", value: "Bac +2" },
        { label: "Durée", value: "2 semestres — 60 ECTS" },
        { label: "Site", value: "Vélizy" },
        { label: "Discipline", value: "Informatique & Réseaux télécom" },
      ],
      couleur: "from-amber-500 to-orange-500",
      futur: true,
    },
  ],

  entreprises: [
    {
      nom: "ATERMES",
      type: "Alternance",
      periode: "Septembre 2025 – Juin 2026",
      lieu: "Yvelines",
      description: "La Société ATERMES, créée en 1989, est devenue un groupe composé de plus de 150 personnes. ATERMES a développé des compétences sur ses quatre métiers clés : Mécanique, Électronique, Optronique et Logiciel.",
      missions: [
        "Administration systèmes et réseaux",
        "Mise en place de services informatiques",
        "Support technique et maintenance",
        "Participation aux projets d'infrastructure",
      ],
      secteur: "Industrie de défense & haute technologie",
      effectif: "+150 personnes",
      fondation: "1989",
      couleur: "from-red-700 to-rose-800",
    },
    {
      nom: "Mairie de Coignières",
      type: "Stage",
      periode: "28 avril – 25 juin 2025 (8 semaines)",
      lieu: "Coignières, Yvelines (78)",
      description: "Stage de 8 semaines au sein de la Direction des Systèmes d'Information (DSI) de la Mairie de Coignières. J'ai participé à l'administration du parc informatique, la supervision réseau et le support aux agents municipaux.",
      missions: [
        "Installation et configuration d'un serveur HP ProLiant sous Debian 12",
        "Déploiement de Zabbix 6.0 pour la supervision réseau",
        "Analyse et schématisation de l'infrastructure réseau",
        "Support technique des agents municipaux",
        "Déplacements dans les écoles, CCAS et MDJ pour résoudre incidents réseau, VPN et matériel",
        "Création de comptes utilisateurs (GLPI, messagerie pro)",
      ],
      secteur: "Collectivité territoriale",
      effectif: "Service DSI",
      couleur: "from-emerald-600 to-teal-700",
    },
  ],

  apropos: {
    parcours: [
      { titre: "BTS SIO option SISR — 2ème année", ecole: "H3 Campus", periode: "Sept. 2025 – Juin 2026" },
      { titre: "BTS SIO option SISR — 1ère année", ecole: "IPSSI SQY", periode: "Sept. 2024 – Juin 2025" },
      { titre: "Baccalauréat Technologique", ecole: "Lycée La Plaine de Neauphle", periode: "Sept. 2023 – Août 2024" },
      { titre: "Brevet des Collèges", ecole: "Gustave Courbet", periode: "Juin 2021 · Mention AB" },
    ],
  },

  competences: [
    { categorie: "Systèmes", icon: "🖥️", items: ["Debian 12", "Administration Linux", "VirtualBox", "Gestion utilisateurs", "XAMPP", "Windows Server"] },
    { categorie: "Réseaux", icon: "🌐", items: ["Configuration réseau", "VPN", "Cisco Packet Tracer", "Schémas réseau", "VLANs", "802.1Q"] },
    { categorie: "Sécurité", icon: "🔒", items: ["SSH sécurisé", "Kali Linux", "Étude du 2FA", "Antivirus", "WPA2-PSK", "TLS/SSL"] },
    { categorie: "Supervision", icon: "📊", items: ["Zabbix 6.0", "Monitoring CPU/RAM", "Tableaux de bord", "Alertes réseau"] },
    { categorie: "Gestion de parc", icon: "🗂️", items: ["GLPI", "OCS Inventory", "GPO Windows Server", "FileZilla FTPS", "Active Directory"] },
    { categorie: "Outils & Dev", icon: "⚙️", items: ["Pack Microsoft Office", "Trello", "Canva", "Figma", "HTML/CSS/JS"] },
  ],

  langues: [
    { langue: "Anglais", niveau: "Intermédiaire", stars: 3 },
    { langue: "Allemand", niveau: "Notions", stars: 2 },
  ],

  contact: {
    email: "mehdiahmiddouch78@gmail.com",
    linkedin: "https://www.linkedin.com/in/mehdi-ahmiddouch-bb491b341/",
    github: "https://github.com/mehdi7881",
    localisation: "Trappes, Île-de-France",
    phone: "07 67 09 34 20",
  },
};

// ─── PROJETS ─────────────────────────────────────────────────────────────────
export const PROJETS = [
  // ── ENTREPRISE ──
  {
    id: "zabbix-supervision",
    titre: "Infrastructure Debian + Supervision Zabbix",
    courte: "Serveur HP ProLiant Debian 12 avec monitoring réseau Zabbix",
    description: "Durant mon stage de 8 semaines à la Mairie de Coignières, j'ai installé et configuré un serveur HP ProLiant sous Debian 12, puis déployé Zabbix 6.0 pour assurer la supervision du réseau et des hôtes Windows. J'ai créé des tableaux de bord personnalisés pour monitorer l'utilisation CPU, RAM et espace disque en temps réel.",
    contexte: "Besoin de superviser l'infrastructure informatique de la mairie en temps réel.",
    objectif: "Mettre en place une solution de monitoring centralisée pour surveiller les serveurs et postes du réseau.",
    resultat: "Tableau de bord Zabbix opérationnel avec alertes CPU, RAM et espace disque configurées.",
    technologies: ["Debian 12", "Zabbix 6.0", "Linux", "MariaDB", "Apache2", "Windows Server"],
    categorie: "Infrastructure",
    type: "entreprise",
    missions: [
      "Installation de Debian 12 sur serveur HP ProLiant",
      "Configuration réseau et services système (MariaDB, Apache2)",
      "Déploiement de Zabbix 6.0 (serveur + agents)",
      "Ajout d'hôtes Windows dans l'interface Zabbix",
      "Création de tableaux de bord de supervision",
      "Configuration des alertes (CPU > 90%, espace disque)",
      "Documentation technique de l'installation",
    ],
    images: [
      { src: "/assets/debian-server.JPG", legende: "Serveur Debian 12 + interface Zabbix en production" },
      { src: "/assets/zabbix_dashboard.png", legende: "Tableau de bord Zabbix – supervision CPU et espace disque" },
      { src: "/assets/zabbix-install.png", legende: "Installation réussie de l'interface Zabbix" },
    ],
    documents: [
      { nom: "Documentation Zabbix", fichier: "/assets/Documentation_zabbix.pdf", description: "Guide d'installation et configuration de l'agent Zabbix" },
    ],
    couleur: "from-blue-600 to-cyan-500",
    icon: "📊",
  },
  {
    id: "infrastructure-reseau",
    titre: "Infrastructure Réseau Mairie de Coignières",
    courte: "Analyse et schématisation de l'infrastructure réseau de la mairie",
    description: "Analyse complète de l'infrastructure réseau de la Mairie de Coignières. Réalisation de schémas de topologie réseau incluant la segmentation par VLANs, la configuration des points d'accès Wi-Fi avec différents niveaux de sécurité (WPA2-PSK, SSID diffusé/non diffusé).",
    contexte: "Besoin de documenter et cartographier l'infrastructure réseau existante de la mairie.",
    objectif: "Produire une documentation réseau complète et des schémas de topologie à jour.",
    resultat: "Documentation réseau complète avec schémas VLANs et inventaire des équipements actifs.",
    technologies: ["Cisco Packet Tracer", "VLANs", "WPA2-PSK", "Documentation réseau"],
    categorie: "Réseau",
    type: "entreprise",
    missions: [
      "Audit de l'infrastructure réseau existante",
      "Réalisation du schéma de topologie réseau",
      "Documentation des VLANs (Admin, Guests, Organisation)",
      "Analyse des points d'accès Wi-Fi et niveaux de sécurité",
      "Identification des équipements actifs (commutateurs, routeurs)",
      "Rédaction de la documentation technique",
    ],
    images: [
      { src: "/assets/assiz.png", legende: "Schéma réseau avec segmentation VLANs et points d'accès" },
      { src: "/assets/dylan.png", legende: "Topologie réseau – commutation et interconnexion" },
    ],
    documents: [],
    couleur: "from-emerald-600 to-teal-500",
    icon: "🌐",
  },
  {
    id: "gestion-parc",
    titre: "Déploiement OCS Inventory + GLPI + GPO",
    courte: "Solution complète de gestion de parc avec inventaire automatisé via GPO",
    description: "Mise en place d'une solution complète de gestion de parc informatique avec GLPI et OCS Inventory. Déploiement automatisé des agents OCS via stratégie de groupe (GPO) sur les postes Windows du domaine, permettant un inventaire automatique et centralisé.",
    contexte: "Besoin de centraliser l'inventaire du parc et le suivi des équipements.",
    objectif: "Mettre en place une solution inventaire + gestion de parc et automatiser le déploiement de l'agent sur les postes.",
    resultat: "Inventaire automatisé et centralisé, parc visible dans GLPI, déploiement agent industrialisé via GPO.",
    technologies: ["GLPI", "OCS Inventory", "Windows Server", "GPO", "Active Directory"],
    categorie: "Gestion de parc",
    type: "entreprise",
    missions: [
      "Installation et configuration de GLPI",
      "Déploiement d'OCS Inventory Server",
      "Liaison GLPI ↔ OCS pour synchronisation automatique",
      "Préparation du package agent OCS",
      "Déploiement de l'agent via GPO sur les postes du domaine",
      "Vérification de la remontée des machines",
    ],
    images: [],
    documents: [],
    couleur: "from-amber-600 to-yellow-500",
    icon: "🗂️",
  },
  {
    id: "virtualisation",
    titre: "Mise en place d'un serveur FTPS (FileZilla)",
    courte: "Serveur FTP sécurisé en FTPS pour échanges internes/externes",
    description: "Mise en place d'un serveur FileZilla en mode FTPS (FTP over TLS/SSL) pour le transfert sécurisé de fichiers. Contexte : besoin de mettre à disposition un partage de fichiers sécurisé pour des échanges internes et externes.",
    contexte: "Besoin de mettre à disposition un partage de fichiers sécurisé pour des échanges internes/externes.",
    objectif: "Déployer un serveur FTP sécurisé en FTPS afin de chiffrer les transferts et renforcer la confidentialité.",
    resultat: "Service opérationnel : transferts chiffrés, accès contrôlé par comptes et permissions.",
    technologies: ["VirtualBox", "FileZilla Server", "FTPS", "TLS/SSL", "Windows Server"],
    categorie: "Infrastructure",
    type: "entreprise",
    missions: [
      "Installation de FileZilla Server sur VM Windows Server",
      "Activation du FTPS (TLS)",
      "Paramétrage réseau (ports / accès)",
      "Tests de connexion sécurisée",
      "Création de comptes et droits d'accès",
      "Documentation de la procédure",
    ],
    images: [],
    documents: [],
    couleur: "from-sky-600 to-indigo-500",
    icon: "💻",
  },

  // ── SCOLAIRES / PERSONNELS ──
  {
    id: "projet-dylan",
    titre: "Projet DYLAN — Insertion dynamique VLAN",
    courte: "Insertion dynamique des PC portables dans leur VLAN à la Maison des Ligues",
    description: "Ce projet vise à permettre l'insertion dynamique des PC portables dans le VLAN correspondant à leur structure lorsqu'ils sont connectés à une prise Ethernet commune dans les salles de réunion de la Maison des Ligues (M2L). Réalisé dans le cadre des projets AP1 à l'IPSSI.",
    contexte: "La Maison des Ligues accueille plusieurs structures qui partagent des prises réseau communes. Chaque PC doit rejoindre automatiquement son VLAN.",
    objectif: "Configurer une infrastructure réseau permettant l'insertion dynamique des équipements dans le bon VLAN selon leur identité.",
    resultat: "Infrastructure réseau fonctionnelle avec affectation automatique des VLANs par structure.",
    technologies: ["Cisco Packet Tracer", "VLANs", "802.1Q", "Switches Cisco"],
    categorie: "Réseau",
    type: "scolaire",
    missions: [
      "Analyse du besoin et de l'infrastructure existante",
      "Conception de la topologie réseau avec VLANs",
      "Configuration des switches Cisco",
      "Mise en place du 802.1Q (trunk)",
      "Tests de connectivité entre VLANs",
      "Documentation et schéma réseau",
    ],
    images: [
      { src: "/assets/dylan.png", legende: "Schéma réseau du projet DYLAN – topologie Cisco Packet Tracer" },
    ],
    documents: [],
    couleur: "from-blue-600 to-indigo-500",
    icon: "🔀",
  },
  {
    id: "projet-assiz",
    titre: "Projet ASSIZ — Infrastructure Wi-Fi Escrime",
    courte: "Infrastructure Wi-Fi temporaire sécurisée pour les VIèmes assises nationales de l'Escrime",
    description: "Projet visant à concevoir et déployer une infrastructure Wi-Fi temporaire pour les VIèmes assises nationales de l'Escrime. La mission : créer un réseau Wi-Fi temporaire bien sécurisé, avec des accès séparés pour les invités et le staff.",
    contexte: "Les assises nationales de l'Escrime nécessitent un réseau Wi-Fi temporaire sécurisé avec séparation des accès.",
    objectif: "Déployer une infrastructure Wi-Fi temporaire avec segmentation invités/staff et sécurisation des accès.",
    resultat: "Infrastructure Wi-Fi opérationnelle avec VLANs séparés, WPA2-PSK pour le staff et portail captif pour les invités.",
    technologies: ["Wi-Fi", "VLANs", "WPA2-PSK", "Cisco Packet Tracer", "Points d'accès"],
    categorie: "Réseau",
    type: "scolaire",
    missions: [
      "Analyse des besoins en connectivité",
      "Conception de l'architecture Wi-Fi temporaire",
      "Configuration des points d'accès (SSID staff / invités)",
      "Segmentation réseau avec VLANs",
      "Sécurisation WPA2-PSK pour le staff",
      "Tests et validation de l'infrastructure",
    ],
    images: [
      { src: "/assets/assiz.png", legende: "Schéma réseau Wi-Fi temporaire – Projet ASSIZ" },
    ],
    documents: [],
    couleur: "from-emerald-600 to-green-500",
    icon: "📡",
  },
  {
    id: "cybersecurite-linux",
    titre: "Cybersécurité & Linux",
    courte: "Étude du 2FA, VM Kali Linux et accès SSH sécurisé",
    description: "Étude des mécanismes d'authentification à deux facteurs (2FA) et de leurs vulnérabilités, configuration d'une machine virtuelle Kali Linux pour des tests de pénétration, et mise en place d'un accès SSH sécurisé avec clés asymétriques.",
    contexte: "TP de sécurité informatique à l'IPSSI — comprendre les attaques et les défenses.",
    objectif: "Comprendre le contournement du 2FA et sécuriser un accès distant via SSH.",
    resultat: "Maîtrise des techniques d'attaque 2FA et d'un accès SSH sécurisé par clés RSA.",
    technologies: ["Kali Linux", "SSH", "VirtualBox", "2FA", "RSA"],
    categorie: "Sécurité",
    type: "scolaire",
    missions: [
      "Configuration d'une VM Kali Linux sous VirtualBox",
      "Étude du contournement de l'authentification 2FA",
      "Mise en place d'un accès SSH avec clés RSA",
      "Tests de sécurité en environnement isolé",
      "Analyse des vulnérabilités d'authentification",
      "Rédaction d'un rapport de sécurité",
    ],
    images: [
      { src: "/assets/hacked.png", legende: "Environnement de test cybersécurité" },
    ],
    documents: [],
    couleur: "from-red-600 to-orange-500",
    icon: "🔒",
  },
  {
    id: "site-web",
    titre: "Développement Web — Site Vitrine",
    courte: "Site web HTML/CSS/JS avec charte graphique Figma",
    description: "Dans le cadre du projet AP1 à l'IPSSI, création d'un site vitrine complet en HTML, CSS et JavaScript. Conception de la charte graphique avec Figma, création des visuels (bannières, logos), et intégration de l'ensemble des contenus.",
    contexte: "Projet AP1 IPSSI — création d'une entreprise fictive avec présence web.",
    objectif: "Créer un site vitrine complet avec charte graphique professionnelle.",
    resultat: "Site web opérationnel avec design cohérent et contenu complet.",
    technologies: ["HTML", "CSS", "JavaScript", "Figma", "Canva"],
    categorie: "Développement",
    type: "scolaire",
    missions: [
      "Conception de la maquette sur Figma",
      "Création de la charte graphique",
      "Développement du site en HTML/CSS/JS",
      "Création des bannières et éléments graphiques",
      "Intégration du contenu (produits, services)",
      "Optimisation responsive",
    ],
    images: [
      { src: "/assets/githubVrai.png", legende: "Aperçu du projet sur GitHub" },
    ],
    documents: [],
    couleur: "from-violet-600 to-purple-500",
    icon: "🌍",
  },
];

// ─── VEILLE ───────────────────────────────────────────────────────────────────
export const VEILLE = [
  {
    titre: "Ransomware as a Service (RaaS)",
    date: "2025 – 2026",
    resume: "Le modèle RaaS permet à des cybercriminels de louer des ransomwares à d'autres attaquants via des plateformes spécialisées, facilitant la multiplication des attaques ciblées contre les entreprises et collectivités. Ce modèle a notamment été utilisé par des groupes comme LockBit ou BlackCat.",
    source: "Articles cybersécurité spécialisés",
    image: "/assets/ransomware.webp",
    lien: null,
    projetId: "cybersecurite-linux",
  },
  {
    titre: "Cybersécurité et authentification — contournement du 2FA",
    date: "2024",
    resume: "Étude des mécanismes d'authentification à deux facteurs et de leurs vulnérabilités : attaques par phishing de session (evilginx), SIM swapping, et contournement via API. Analyse des bonnes pratiques pour sécuriser les accès.",
    source: "Travaux pratiques — IPSSI",
    image: "/assets/hacked.png",
    lien: null,
    projetId: "cybersecurite-linux",
  },
];
