// ═══════════════════════════════════════════════════════════════
// data.js — BTS SIO SISR — Mehdi Ahmiddouch 2026
// ═══════════════════════════════════════════════════════════════

export const PROFILE = {
  nom: "Mehdi Ahmiddouch",
  age: 18,
  formation: "BTS SIO option SISR",
  ecole: "H3 Campus",
  tagline: "Etudiant en BTS SIO SISR, passionné par l'administration systèmes, réseaux et la cybersécurité.",
  objectif: "Devenir administrateur systèmes et réseaux, avec une spécialisation en cybersécurité.",
  phone: "07 67 09 34 20",
  cv: "/assets/CV_Mehdi_Amd.pdf",

  presentation: {
    texte: "Je suis Mehdi Ahmiddouch, 18 ans, étudiant en BTS SIO spécialité SISR. Curieux, motivé et passionné par la cybersécurité, j'explore les domaines du réseau, de la virtualisation et de l'automatisation pour bâtir des systèmes solides et efficaces. Mon objectif : évoluer dans un environnement où la sécurité informatique et l'innovation technique vont de pair.",
    points: [
      "Passionné par la cybersécurité et les infrastructures réseau",
      "Curieux et autonome dans l'apprentissage de nouvelles technologies",
      "Rigoureux dans la mise en place et la documentation de projets",
      "À l'aise aussi bien en environnement Linux qu'en Windows Server",
    ],
  },

  ecoles: [
    {
      nom: "H3 Campus - IPSSI SQY",
      logo: "/assets/logo-h3campus.png",
      periode: "Septembre 2025 - Juin 2026",
      diplome: "BTS SIO option SISR - 2ème année",
      lieu: "Saint-Quentin-en-Yvelines",
      description: "H3 Campus est une grande école d'informatique. En 2ème année de BTS SIO SISR, j'approfondis mes compétences en administration systèmes, réseaux, cybersécurité et gestion de parc, en alternance chez ATERMES.",
      matieres: ["Administration systèmes", "Réseaux & sécurité", "Cybersécurité", "Gestion de parc", "Anglais technique"],
      couleur: "from-sky-600 to-blue-700",
      futur: false,
    },
    {
      nom: "IPSSI SQY",
      logo: "/assets/logo-h3campus.png",
      periode: "Septembre 2024 - Juin 2025",
      diplome: "BTS SIO option SISR - 1ère année",
      lieu: "Saint-Quentin-en-Yvelines",
      description: "L'IPSSI est une grande école d'informatique spécialisée dans les métiers de la sécurité et des systèmes d'information. En 1ère année, j'ai acquis les bases solides en administration systèmes, réseaux et sécurité informatique.",
      matieres: ["Linux & Windows Server", "Réseaux TCP/IP", "Virtualisation", "Sécurité informatique", "Projets AP1"],
      couleur: "from-violet-600 to-purple-700",
      futur: false,
    },
    {
      nom: "IUT de Vélizy-Rambouillet - UVSQ",
      logo: "/assets/logo-uvsq.jpg",
      periode: "Septembre 2026 - Juin 2027 (visée)",
      diplome: "Licence Pro MRIT parcours ASUR - Cybersécurité",
      lieu: "Vélizy-Villacoublay (78)",
      description: "Mon projet de poursuite d'études après le BTS SIO SISR. La Licence Pro MRIT parcours ASUR me permettra de me spécialiser en cybersécurité et administration réseau.",
      matieres: ["Cybersécurité", "Administration réseaux", "Télécommunications", "Sécurité des SI", "Formation en ligne"],
      infos: [
        { label: "Niveau requis", value: "Bac +2" },
        { label: "Durée", value: "2 semestres - 60 ECTS" },
        { label: "Site", value: "Vélizy" },
        { label: "Discipline", value: "Informatique & Réseaux télécom" },
      ],
      couleur: "from-amber-500 to-orange-500",
      futur: true,
    },
  ],

  entreprises: [
    {
      nom: "ATERMES",
      logo: "/assets/logo-atermes.png",
      type: "Alternance",
      periode: "Septembre 2025 - Juin 2026",
      lieu: "Yvelines",
      description: "La Société ATERMES, créée en 1989, est devenue un groupe composé de plus de 150 personnes. ATERMES a développé des compétences sur ses quatre métiers clés : Mécanique, Électronique, Optronique et Logiciel.",
      missions: [
        "Administration systèmes et réseaux",
        "Mise en place de services informatiques",
        "Support technique et maintenance",
        "Participation aux projets d'infrastructure",
      ],
      secteur: "Industrie de défense & haute technologie",
      effectif: "+150 personnes",
      fondation: "1989",
      couleur: "from-red-700 to-rose-800",
    },
    {
      nom: "Mairie de Coignières",
      logo: "/assets/logo-coignieres.jpg",
      type: "Stage",
      periode: "28 avril - 25 juin 2025 (8 semaines)",
      lieu: "Coignières, Yvelines (78)",
      description: "Stage de 8 semaines au sein de la DSI de la Mairie de Coignières. J'ai participé à l'administration du parc informatique, la supervision réseau et le support aux agents municipaux.",
      missions: [
        "Installation et configuration d'un serveur HP ProLiant sous Debian 12",
        "Déploiement de Zabbix 6.0 pour la supervision réseau",
        "Analyse et schématisation de l'infrastructure réseau",
        "Support technique des agents municipaux",
        "Déplacements dans les écoles, CCAS et MDJ pour incidents réseau et VPN",
        "Création de comptes utilisateurs (GLPI, messagerie pro)",
      ],
      secteur: "Collectivité territoriale",
      effectif: "Service DSI",
      couleur: "from-emerald-600 to-teal-700",
    },
  ],

  apropos: {
    parcours: [
      { titre: "BTS SIO option SISR - 2ème année", ecole: "H3 Campus",                   periode: "Sept. 2025 - Juin 2026" },
      { titre: "BTS SIO option SISR - 1ère année", ecole: "IPSSI SQY",                   periode: "Sept. 2024 - Juin 2025" },
      { titre: "Baccalauréat Technologique",        ecole: "Lycée La Plaine de Neauphle", periode: "Sept. 2023 - Août 2024" },
      { titre: "Brevet des Collèges",               ecole: "Gustave Courbet",             periode: "Juin 2021 - Mention AB" },
    ],
  },

  competences: [
    { categorie: "Systèmes",        icon: "PC",  items: ["Debian 12", "Ubuntu 22.04", "Administration Linux", "VirtualBox", "Gestion utilisateurs", "XAMPP", "Windows Server"] },
    { categorie: "Réseaux",         icon: "NET", items: ["Configuration réseau", "VPN", "Cisco Packet Tracer", "Schémas réseau", "VLANs", "802.1Q"] },
    { categorie: "Sécurité",        icon: "SEC", items: ["SSH sécurisé", "Kali Linux", "Étude du 2FA", "Antivirus", "WPA2-PSK", "TLS/SSL"] },
    { categorie: "Supervision",     icon: "MON", items: ["Zabbix 6.0", "Nagios Core", "Monitoring CPU/RAM", "Tableaux de bord", "Alertes réseau"] },
    { categorie: "Gestion de parc", icon: "PAR", items: ["GLPI", "OCS Inventory", "GPO Windows Server", "FileZilla FTPS", "Active Directory"] },
    { categorie: "Outils & Dev",    icon: "OTL", items: ["Pack Microsoft Office", "Trello", "Canva", "Figma", "HTML/CSS/JS"] },
  ],

  langues: [
    { langue: "Anglais",  niveau: "Intermédiaire", stars: 3 },
    { langue: "Allemand", niveau: "Notions",       stars: 2 },
  ],

  contact: {
    email:        "mehdiahmiddouch78@gmail.com",
    linkedin:     "https://www.linkedin.com/in/mehdi-ahmiddouch-bb491b341/",
    github:       "https://github.com/mehdi7881",
    localisation: "Trappes, Île-de-France",
    phone:        "07 67 09 34 20",
  },
};

export const PROJETS = [

  // ─── ENTREPRISE ───────────────────────────────────────────────

  {
    id: "zabbix-supervision",
    titre: "Infrastructure Debian + Supervision Zabbix",
    courte: "Serveur HP ProLiant Debian 12 avec monitoring réseau Zabbix",
    description: "Durant mon stage de 8 semaines à la Mairie de Coignières, j'ai installé et configuré un serveur HP ProLiant sous Debian 12, puis déployé Zabbix 6.0 pour assurer la supervision du réseau et des hôtes Windows.",
    contexte: "Besoin de superviser l'infrastructure informatique de la mairie en temps réel.",
    objectif: "Mettre en place une solution de monitoring centralisée pour surveiller les serveurs et postes du réseau.",
    resultat: "Tableau de bord Zabbix opérationnel avec alertes CPU, RAM et espace disque configurées.",
    technologies: ["Debian 12", "Zabbix 6.0", "Linux", "MariaDB", "Apache2", "Windows Server"],
    categorie: "Infrastructure",
    type: "entreprise",
    // ✅ Logo Zabbix ajouté (comme Nagios)
    logo: "/assets/zabbix.webp",
    missions: [
      "Installation de Debian 12 sur serveur HP ProLiant",
      "Configuration réseau et services système (MariaDB, Apache2)",
      "Déploiement de Zabbix 6.0 (serveur + agents)",
      "Ajout d'hôtes Windows dans l'interface Zabbix",
      "Création de tableaux de bord de supervision",
      "Configuration des alertes (CPU > 90%, espace disque)",
      "Documentation technique de l'installation",
    ],
    images: [
      { src: "/assets/debian-server.JPG",    legende: "Serveur Debian 12 HP ProLiant en production" },
      { src: "/assets/zabbix_dashboard.png", legende: "Tableau de bord Zabbix - supervision CPU et RAM" },
      { src: "/assets/zabbix-install.png",   legende: "Installation réussie de l'interface Zabbix" },
    ],
    documents: [
      { nom: "Documentation Zabbix", fichier: "/assets/Documentation_zabbix.pdf", description: "Guide d'installation et configuration de Zabbix 6.0" },
    ],
    couleur: "from-red-700 to-red-900",
    icon: "MON",
  },

  {
    id: "infrastructure-reseau",
    titre: "Infrastructure Réseau Mairie de Coignières",
    courte: "Analyse et schématisation de l'infrastructure réseau de la mairie",
    description: "Analyse complète de l'infrastructure réseau de la Mairie de Coignières. Réalisation de schémas de topologie réseau incluant la segmentation par VLANs et la configuration des points d'accès Wi-Fi.",
    contexte: "Besoin de documenter et cartographier l'infrastructure réseau existante de la mairie.",
    objectif: "Produire une documentation réseau complète et des schémas de topologie à jour.",
    resultat: "Documentation réseau complète avec schémas VLANs et inventaire des équipements actifs.",
    technologies: ["Cisco Packet Tracer", "VLANs", "WPA2-PSK", "Documentation réseau"],
    categorie: "Réseau",
    type: "entreprise",
    missions: [
      "Audit de l'infrastructure réseau existante",
      "Réalisation du schéma de topologie réseau",
      "Documentation des VLANs (Admin, Guests, Organisation)",
      "Analyse des points d'accès Wi-Fi et niveaux de sécurité",
      "Identification des équipements actifs (commutateurs, routeurs)",
      "Rédaction de la documentation technique",
    ],
    images: [
      { src: "/assets/inframairie.png", legende: "Schéma d'infrastructure réseau - VLANs, switches, pare-feu" },
      { src: "/assets/borne-ccas.JPG",  legende: "Borne CCAS - intervention terrain réseau et VPN" },
    ],
    documents: [],
    couleur: "from-emerald-600 to-teal-500",
    icon: "NET",
  },

  {
    id: "gestion-parc",
    titre: "Déploiement OCS Inventory + GLPI + GPO",
    courte: "Solution complète de gestion de parc avec inventaire automatisé via GPO",
    description: "Mise en place d'une solution complète de gestion de parc informatique avec GLPI et OCS Inventory. Déploiement automatisé des agents OCS via GPO sur les postes Windows du domaine.",
    contexte: "Besoin de centraliser l'inventaire du parc et le suivi des équipements.",
    objectif: "Mettre en place une solution inventaire + gestion de parc et automatiser le déploiement de l'agent.",
    resultat: "Inventaire automatisé et centralisé, parc visible dans GLPI, déploiement agent via GPO.",
    technologies: ["GLPI", "OCS Inventory", "Windows Server", "GPO", "Active Directory"],
    categorie: "Gestion de parc",
    type: "entreprise",
    missions: [
      "Installation et configuration de GLPI",
      "Déploiement d'OCS Inventory Server",
      "Liaison GLPI - OCS pour synchronisation automatique",
      "Préparation du package agent OCS",
      "Déploiement de l'agent via GPO sur les postes du domaine",
      "Vérification de la remontée des machines",
    ],
    images: [{ src: "/assets/ocsGLPIlogo.png", legende: "OCS Inventory + GLPI" }],
    documents: [],
    couleur: "from-amber-600 to-yellow-500",
    icon: "PAR",
  },

  {
    id: "virtualisation",
    titre: "Mise en place d'un serveur FTPS (FileZilla)",
    courte: "Serveur FTP sécurisé en FTPS pour échanges internes/externes",
    description: "Mise en place d'un serveur FileZilla en mode FTPS (FTP over TLS/SSL) pour le transfert sécurisé de fichiers.",
    contexte: "Besoin de mettre à disposition un partage de fichiers sécurisé pour des échanges internes/externes.",
    objectif: "Déployer un serveur FTP sécurisé en FTPS afin de chiffrer les transferts.",
    resultat: "Service opérationnel : transferts chiffrés, accès contrôlé par comptes et permissions.",
    technologies: ["VirtualBox", "FileZilla Server", "FTPS", "TLS/SSL", "Windows Server"],
    categorie: "Infrastructure",
    type: "entreprise",
    // ✅ Logo FileZilla ajouté (comme Nagios/Zabbix)
    logo: "/assets/filezilla.webp",
    missions: [
      "Installation de FileZilla Server sur VM Windows Server",
      "Activation du FTPS (TLS)",
      "Paramétrage réseau (ports / accès)",
      "Tests de connexion sécurisée",
      "Création de comptes et droits d'accès",
      "Documentation de la procédure",
    ],
    images: [],
    documents: [],
    couleur: "from-red-600 to-orange-600",
    icon: "SRV",
  },

  // ─── SCOLAIRES ────────────────────────────────────────────────

  {
    id: "glpi-ocs-m2l",
    titre: "OCS Inventory + GLPI - Gestion de parc M2L",
    courte: "Solution d'inventaire et de ticketing pour la Maison des Ligues (M2L)",
    description: "Mise en place d'une solution complète de gestion de parc informatique (OCS Inventory + GLPI) dans le contexte de la Maison des Ligues (M2L). Le serveur a été déployé sur une VM Ubuntu via Proxmox avec une pile LAMP.",
    contexte: "La Maison des Ligues (M2L) avait besoin d'une solution de gestion centralisée de son parc informatique.",
    objectif: "Mettre en place un inventaire automatique des postes et centraliser les informations du parc.",
    resultat: "Serveur OCS Inventory et GLPI fonctionnel, inventaire automatisé, intégration dans GLPI.",
    technologies: ["Proxmox", "Ubuntu", "Apache2", "MySQL", "PHP", "OCS Inventory", "GLPI"],
    categorie: "Gestion de parc",
    type: "scolaire",
    numero: "RP2",
    periode: "Février 2026 - Avril 2026",
    lieu: "H3 Campus - Poissy",
    missions: [
      "Installation du serveur Ubuntu sur Proxmox",
      "Mise en place de la pile LAMP (Apache, MySQL, PHP)",
      "Installation et configuration d'OCS Inventory Server",
      "Installation et configuration de GLPI",
      "Configuration du plugin OCS dans GLPI",
      "Installation de l'agent OCS sur un poste client",
      "Mise en place de la synchronisation OCS vers GLPI",
      "Tests de remontée des informations et validation",
      "Création d'utilisateurs et droits d'accès",
    ],
    images: [{ src: "/assets/ocsGLPIlogo.png", legende: "OCS Inventory + GLPI - M2L" }],
    documents: [
      {
        nom: "Fiche descriptive E6 - GLPI",
        fichier: "/assets/Fiche-descriptive-de-realisation-professionnelle-GLPI.docx",
        description: "Fiche officielle BTS SIO E6 - Administration des systèmes et réseaux",
      },
    ],
    ficheWord: "/assets/Fiche-descriptive-de-realisation-professionnelle-GLPI.docx",
    lienProduction: "https://bit.ly/4sfn9yF",
    couleur: "from-amber-600 to-orange-500",
    icon: "PAR",
  },

  {
    id: "nagios-m2l",
    titre: "Nagios - Supervision réseau M2L",
    courte: "Mise en place de Nagios4 pour la supervision de l'infrastructure de la M2L",
    description: "Installation et configuration de Nagios4 pour superviser les équipements réseau et services critiques de la Maison des Ligues (M2L).",
    contexte: "Aucun outil de supervision n'était en place à la M2L.",
    objectif: "Déployer Nagios4 pour assurer une surveillance continue des équipements.",
    resultat: "Supervision opérationnelle, notifications mail, seuils critiques définis, interface web accessible.",
    technologies: ["Proxmox", "Ubuntu", "Nagios Core", "Apache", "Nagios Plugins", "Postfix", "SSH", "SNMP"],
    categorie: "Supervision",
    type: "scolaire",
    numero: "RP2",
    periode: "Décembre 2025 - Mars 2026",
    lieu: "H3 Campus",
    missions: [
      "Installation de Nagios4 sur serveur Ubuntu (VM Proxmox)",
      "Configuration des hôtes (hosts) à superviser",
      "Configuration des services (ping, HTTP, SSH, CPU)",
      "Mise en place des notifications par mail (Postfix)",
      "Définition des seuils critiques et warnings",
      "Configuration SNMP sur les équipements réseau",
      "Tests remontée états UP/DOWN et simulation de panne",
    ],
    images: [
      { src: "/assets/logo-nagios.png", legende: "Nagios Core - Solution de supervision réseau" },
    ],
    documents: [
      {
        nom: "Fiche descriptive E6 - Nagios",
        fichier: "/assets/Fiche-descriptive-de-realisation-professionnelle-NAGIOS.docx",
        description: "Fiche officielle BTS SIO E6 - Administration des systèmes et réseaux",
      },
    ],
    ficheWord: "/assets/Fiche-descriptive-de-realisation-professionnelle-NAGIOS.docx",
    lienProduction: "https://bit.ly/4sfn9yF",
    couleur: "from-slate-700 to-slate-900",
    logo: "/assets/logo-nagios.png",
    icon: "MON",
  },

  {
    id: "ap2-m2l",
    titre: "AP2 - Projets DYLAN & ASSIZ (Maison des Ligues)",
    courte: "Insertion dynamique VLAN et infrastructure Wi-Fi temporaire pour la M2L",
    description: "Atelier de Professionnalisation N°2 réalisé en groupe dans le contexte de la Maison des Ligues (M2L). Deux missions : DYLAN (MAC-based VLAN) et ASSIZ (Wi-Fi temporaire sécurisé pour les assises nationales de l'Escrime).",
    contexte: "La Maison des Ligues héberge plusieurs organisations sportives partageant un réseau commun.",
    objectif: "Mission 1 : insertion dynamique des PC dans le bon VLAN. Mission 2 : infrastructure Wi-Fi temporaire sécurisée.",
    resultat: "Solution MAC-based VLAN pour DYLAN. Infrastructure Wi-Fi à 3 points d'accès segmentés pour ASSIZ.",
    technologies: ["Cisco Packet Tracer", "MAC-based VLAN", "802.1Q", "Wi-Fi", "WPA2-PSK", "SSID", "Switch Cisco"],
    categorie: "Réseau",
    type: "scolaire",
    missions: [
      "Analyse du contexte de la Maison des Ligues",
      "Étude et comparaison de 3 solutions VLAN",
      "Choix de la solution MAC-based VLAN pour DYLAN",
      "Conception de l'infrastructure Wi-Fi temporaire pour ASSIZ",
      "Maquettage sur Cisco Packet Tracer",
      "Rédaction du dossier AP2 et présentation PowerPoint",
    ],
    images: [
      { src: "/assets/dylan.png", legende: "Projet DYLAN - Topologie MAC-based VLAN sur Cisco Packet Tracer" },
      { src: "/assets/assiz.png", legende: "Projet ASSIZ - Infrastructure Wi-Fi temporaire segmentée" },
    ],
    documents: [
      { nom: "Dossier AP2 - Rapport complet",  fichier: "/assets/AP2_M2L.docx",           description: "Rapport Word complet : contexte, solutions, comparaison, annexes" },
      { nom: "Présentation AP2 - PowerPoint",  fichier: "/assets/AP2_presentation.pptx",  description: "Support de présentation du projet devant le jury" },
    ],
    couleur: "from-blue-600 to-indigo-500",
    icon: "ENT",
  },

  {
    id: "cybersecurite-linux",
    titre: "Cybersécurité & Linux",
    courte: "Étude du 2FA, VM Kali Linux et accès SSH sécurisé",
    description: "Étude des mécanismes d'authentification à deux facteurs (2FA) et de leurs vulnérabilités, configuration d'une machine virtuelle Kali Linux pour des tests de pénétration, et mise en place d'un accès SSH sécurisé avec clés asymétriques.",
    contexte: "TP de sécurité informatique à l'IPSSI - comprendre les attaques et les défenses.",
    objectif: "Comprendre le contournement du 2FA et sécuriser un accès distant via SSH.",
    resultat: "Maîtrise des techniques d'attaque 2FA et d'un accès SSH sécurisé par clés RSA.",
    technologies: ["Kali Linux", "SSH", "2FA", "OpenSSL", "VirtualBox", "Metasploit"],
    categorie: "Sécurité",
    type: "scolaire",
    missions: [
      "Installation et configuration de Kali Linux",
      "Étude des mécanismes 2FA (TOTP, SMS, clés physiques)",
      "Démonstration de contournement 2FA (phishing de session)",
      "Configuration SSH avec clés RSA asymétriques",
      "Tests d'intrusion en environnement virtuel",
      "Rédaction d'un rapport de sécurité",
    ],
    images: [
      { src: "/assets/hacked.png", legende: "TP Cybersécurité - Techniques d'attaque et défense" },
    ],
    documents: [],
    couleur: "from-red-600 to-rose-500",
    icon: "SEC",
  },

  {
    id: "veille-ransomware",
    titre: "Veille : Ransomware as a Service (RaaS)",
    courte: "Analyse de la menace RaaS et évolution des cyberattaques 2025-2026",
    description: "Veille technologique approfondie sur la menace Ransomware as a Service (RaaS). Étude des groupes criminels (NightSpire, LockBit 3.0), de l'utilisation de l'IA par les attaquants, et des mesures ANSSI.",
    contexte: "Les ransomwares représentent la principale menace cyber pour les entreprises et collectivités en 2026.",
    objectif: "Comprendre l'écosystème RaaS et proposer des recommandations de protection.",
    resultat: "Synthèse du panorama des menaces 2025-2026, alignée avec le Panorama ANSSI 2025.",
    technologies: ["Cybersécurité", "ANSSI", "Threat Intelligence", "MITRE ATT&CK"],
    categorie: "Veille",
    type: "scolaire",
    missions: [
      "Suivi des flux RSS ANSSI, LeMagIT, IT-Connect",
      "Analyse du groupe NightSpire et du modèle RaaS",
      "Étude du rapport ANSSI Panorama 2025",
      "Analyse des techniques d'IA utilisées par les attaquants",
      "Étude du contournement 2FA (phishing de session, SIM swapping)",
      "Synthèse et recommandations de protection",
    ],
    images: [{ src: "/assets/ransomware.webp", legende: "Veille - Menace ransomware et RaaS 2026" }],
    documents: [],
    couleur: "from-purple-600 to-violet-500",
    icon: "VLN",
  },

  {
    id: "site-web",
    titre: "Site Web - Projet HTML/CSS/JS",
    courte: "Conception et développement d'un site vitrine en HTML/CSS/JS",
    description: "Conception et développement d'un site web vitrine complet, de la maquette Figma jusqu'au déploiement. Création de la charte graphique, intégration responsive et optimisation UX.",
    contexte: "Projet de développement web à l'IPSSI.",
    objectif: "Concevoir et développer un site web vitrine fonctionnel et responsive.",
    resultat: "Site web opérationnel avec design responsive et identité visuelle cohérente.",
    technologies: ["HTML", "CSS", "JavaScript", "Figma", "Canva"],
    categorie: "Développement",
    type: "scolaire",
    missions: [
      "Conception de la maquette sur Figma",
      "Création de la charte graphique",
      "Développement du site en HTML/CSS/JS",
      "Création des bannières et éléments graphiques",
      "Intégration du contenu (produits, services)",
      "Optimisation responsive",
    ],
    images: [
      { src: "/assets/githubVrai.png", legende: "Aperçu du projet sur GitHub" },
    ],
    documents: [],
    couleur: "from-violet-600 to-purple-500",
    icon: "WEB",
  },
];

export const VEILLE = [
  {
    titre: "Ransomware as a Service : NightSpire, nouveau groupe RaaS",
    date: "Avril 2026",
    resume: "Apparue début 2025, l'enseigne de ransomware NightSpire s'est présentée sous les apparences d'une opération fermée avant de manifester des signes d'ouverture à un modèle RaaS. Cible : entreprises et collectivités.",
    source: "LeMagIT",
    image: "/assets/ransomware.webp",
    lien: "https://www.lemagit.fr/actualites/366641805/Cyberhebdo-du-17-avril-2026",
    projetId: "cybersecurite-linux",
  },
  {
    titre: "ANSSI - Panorama de la cybermenace 2025",
    date: "Mars 2026",
    resume: "L'ANSSI a publié son Panorama de la cybermenace 2025. Les cyberattaques ont progressé de 38% en un an. 43% des collectivités territoriales ont subi au moins une tentative de ransomware en 2025.",
    source: "ANSSI",
    image: "/assets/hacked.png",
    lien: "https://cyber.gouv.fr/",
    projetId: "cybersecurite-linux",
  },
  {
    titre: "NIS 2 : l'ANSSI déploie ReCyF et impose la conformité",
    date: "Mars 2026",
    resume: "Depuis le 17 mars 2026, l'ANSSI met à disposition le Référentiel Cyber France (ReCyF) pour les objectifs de sécurité fixés par la directive NIS 2.",
    source: "ANSSI / IT-Connect",
    image: "/assets/hacked.png",
    lien: "https://www.it-connect.fr/securite-de-etat-lanssi-devoile-sa-feuille-de-route-pour-2026-2027/",
    projetId: "cybersecurite-linux",
  },
  {
    titre: "Cybersécurité 2026 : l'IA au service des attaquants",
    date: "Janvier 2026",
    resume: "Les pirates utilisent l'IA générative et les deepfakes pour des attaques de phishing à grande échelle. 91% des cyberattaques réussies débutent par un email frauduleux.",
    source: "LeMagIT",
    image: "/assets/ransomware.webp",
    lien: "https://www.lemagit.fr/actualites/366637562/Les-8-principales-previsions-en-matiere-de-cybersecurite-pour-2026",
    projetId: "cybersecurite-linux",
  },
  {
    titre: "Contournement du 2FA : techniques d'attaque 2024-2025",
    date: "2024 - 2025",
    resume: "Étude des mécanismes d'authentification à deux facteurs et de leurs vulnérabilités : phishing de session (evilginx), SIM swapping, contournement via API.",
    source: "Travaux pratiques IPSSI",
    image: "/assets/hacked.png",
    lien: null,
    projetId: "cybersecurite-linux",
  },
  {
    titre: "Menaces sur le stockage : ransomware et IA en 2026",
    date: "Décembre 2025",
    resume: "Les attaques par ransomware utilisant l'IA ciblent les vulnérabilités des systèmes de stockage avec des attaques automatisées.",
    source: "LeMagIT",
    image: "/assets/ransomware.webp",
    lien: "https://www.lemagit.fr/conseil/Cybersecurite-ces-menaces-qui-vont-peser-sur-le-stockage-de-donnees-en-2026",
    projetId: "cybersecurite-linux",
  },
];
