export const PROFILE = {
  nom: "Mehdi Ahmiddouch",
  age: 18,
  formation: "BTS SIO option SISR",
  ecole: "H3 Campus",
  tagline: "Etudiant en BTS SIO SISR, passionne par l'administration systemes, reseaux et la cybersecurite.",
  objectif: "Devenir administrateur systemes et reseaux, avec une specialisation en cybersecurite.",
  phone: "07 67 09 34 20",
  cv: "/assets/CV_Mehdi_Amd.pdf",

  presentation: {
    texte: "Je suis Mehdi Ahmiddouch, 18 ans, etudiant en BTS SIO specialite SISR. Curieux, motive et passionne par la cybersecurite, j'explore les domaines du reseau, de la virtualisation et de l'automatisation pour batir des systemes solides et efficaces. Mon objectif : evoluer dans un environnement ou la securite informatique et l'innovation technique vont de pair.",
    points: [
      "Passionne par la cybersecurite et les infrastructures reseau",
      "Curieux et autonome dans l'apprentissage de nouvelles technologies",
      "Rigoureux dans la mise en place et la documentation de projets",
      "A l'aise aussi bien en environnement Linux qu'en Windows Server",
    ],
  },

  ecoles: [
    {
      nom: "H3 Campus",
      logo: "/assets/logo-h3campus.webp",
      periode: "Septembre 2025 - Juin 2026",
      diplome: "BTS SIO option SISR - 2eme annee",
      lieu: "Saint-Quentin-en-Yvelines",
      description: "H3 Campus est une grande ecole d'informatique. En 2eme annee de BTS SIO SISR, j'approfondis mes competences en administration systemes, reseaux, cybersecurite et gestion de parc, en alternance chez ATERMES.",
      matieres: ["Administration systemes", "Reseaux & securite", "Cybersecurite", "Gestion de parc", "Anglais technique"],
      couleur: "from-sky-600 to-blue-700",
      futur: false,
    },
    {
      nom: "IPSSI SQY",
      logo: "/assets/IPSSI.webp",
      periode: "Septembre 2024 - Juin 2025",
      diplome: "BTS SIO option SISR - 1ere annee",
      lieu: "Saint-Quentin-en-Yvelines",
      description: "L'IPSSI est une grande ecole d'informatique specialisee dans les metiers de la securite et des systemes d'information. En 1ere annee, j'ai acquis les bases solides en administration systemes, reseaux et securite informatique.",
      matieres: ["Linux & Windows Server", "Reseaux TCP/IP", "Virtualisation", "Securite informatique", "Projets AP1"],
      couleur: "from-violet-600 to-purple-700",
      futur: false,
    },
    {
      nom: "IUT de Velizy-Rambouillet - UVSQ",
      logo: "/assets/logo-uvsq.jpg",
      periode: "Septembre 2026 - Juin 2027 (visee)",
      diplome: "Licence Pro MRIT parcours ASUR - Cybersecurite",
      lieu: "Velizy-Villacoublay (78)",
      description: "Mon projet de poursuite d'etudes apres le BTS SIO SISR. La Licence Pro MRIT parcours ASUR me permettra de me specialiser en cybersecurite et administration reseau.",
      matieres: ["Cybersecurite", "Administration reseaux", "Telecommunications", "Securite des SI", "Formation en ligne"],
      infos: [
        { label: "Niveau requis", value: "Bac +2" },
        { label: "Duree", value: "2 semestres - 60 ECTS" },
        { label: "Site", value: "Velizy" },
        { label: "Discipline", value: "Informatique & Reseaux telecom" },
      ],
      couleur: "from-amber-500 to-orange-500",
      futur: true,
    },
  ],

  entreprises: [
    {
      nom: "ATERMES",
      logo: "/assets/logo-atermes.png",
      type: "Alternance",
      periode: "Septembre 2025 - Juin 2026",
      lieu: "Yvelines",
      description: "La Societe ATERMES, creee en 1989, est devenue un groupe compose de plus de 150 personnes. ATERMES a developpe des competences sur ses quatre metiers cles : Mecanique, Electronique, Optronique et Logiciel.",
      missions: [
        "Administration systemes et reseaux",
        "Mise en place de services informatiques",
        "Support technique et maintenance",
        "Participation aux projets d'infrastructure",
      ],
      secteur: "Industrie de defense & haute technologie",
      effectif: "+150 personnes",
      fondation: "1989",
      couleur: "from-red-700 to-rose-800",
    },
    {
      nom: "Mairie de Coignieres",
      logo: "/assets/logo-coignieres.jpg",
      type: "Stage",
      periode: "28 avril - 25 juin 2025 (8 semaines)",
      lieu: "Coignieres, Yvelines (78)",
      description: "Stage de 8 semaines au sein de la DSI de la Mairie de Coignieres. J'ai participe a l'administration du parc informatique, la supervision reseau et le support aux agents municipaux.",
      missions: [
        "Installation et configuration d'un serveur HP ProLiant sous Debian 12",
        "Deploiement de Zabbix 6.0 pour la supervision reseau",
        "Analyse et schematisation de l'infrastructure reseau",
        "Support technique des agents municipaux",
        "Deplacements dans les ecoles, CCAS et MDJ pour resoudre incidents reseau, VPN et materiel",
        "Creation de comptes utilisateurs (GLPI, messagerie pro)",
      ],
      secteur: "Collectivite territoriale",
      effectif: "Service DSI",
      couleur: "from-emerald-600 to-teal-700",
    },
  ],

  apropos: {
    parcours: [
      { titre: "BTS SIO option SISR - 2eme annee", ecole: "H3 Campus", periode: "Sept. 2025 - Juin 2026" },
      { titre: "BTS SIO option SISR - 1ere annee", ecole: "IPSSI SQY", periode: "Sept. 2024 - Juin 2025" },
      { titre: "Baccalaureat Technologique", ecole: "Lycee La Plaine de Neauphle", periode: "Sept. 2023 - Aout 2024" },
      { titre: "Brevet des Colleges", ecole: "Gustave Courbet", periode: "Juin 2021 - Mention AB" },
    ],
  },

  competences: [
    { categorie: "Systemes", icon: "PC", items: ["Debian 12", "Ubuntu 22.04", "Administration Linux", "VirtualBox", "Gestion utilisateurs", "XAMPP", "Windows Server"] },
    { categorie: "Reseaux", icon: "NET", items: ["Configuration reseau", "VPN", "Cisco Packet Tracer", "Schemas reseau", "VLANs", "802.1Q"] },
    { categorie: "Securite", icon: "SEC", items: ["SSH securise", "Kali Linux", "Etude du 2FA", "Antivirus", "WPA2-PSK", "TLS/SSL"] },
    { categorie: "Supervision", icon: "MON", items: ["Zabbix 6.0", "Monitoring CPU/RAM", "Tableaux de bord", "Alertes reseau"] },
    { categorie: "Gestion de parc", icon: "PAR", items: ["GLPI", "OCS Inventory", "GPO Windows Server", "FileZilla FTPS"] },
    { categorie: "Outils & Dev", icon: "OTL", items: ["Pack Microsoft Office", "Trello", "Canva", "Figma", "HTML/CSS/JS"] },
  ],

  langues: [
    { langue: "Anglais", niveau: "Intermediaire", stars: 3 },
    { langue: "Allemand", niveau: "Notions", stars: 2 },
  ],

  contact: {
    email: "mehdiahmiddouch78@gmail.com",
    linkedin: "https://www.linkedin.com/in/mehdi-ahmiddouch-bb491b341/",
    github: "https://github.com/mehdi7881",
    localisation: "Trappes, Ile-de-France",
    phone: "07 67 09 34 20",
  },
};

export const PROJETS = [
  {
    id: "zabbix-supervision",
    titre: "Infrastructure Debian + Supervision Zabbix",
    courte: "Serveur HP ProLiant Debian 12 avec monitoring reseau Zabbix",
    description: "Durant mon stage de 8 semaines a la Mairie de Coignieres, j'ai installe et configure un serveur HP ProLiant sous Debian 12, puis deploye Zabbix 6.0 pour assurer la supervision du reseau et des hotes Windows.",
    contexte: "Besoin de superviser l'infrastructure informatique de la mairie en temps reel.",
    objectif: "Mettre en place une solution de monitoring centralisee pour surveiller les serveurs et postes du reseau.",
    resultat: "Tableau de bord Zabbix operationnel avec alertes CPU, RAM et espace disque configurees.",
    technologies: ["Debian 12", "Zabbix 6.0", "Linux", "MariaDB", "Apache2", "Windows Server"],
    categorie: "Infrastructure",
    type: "entreprise",
    missions: [
      "Installation de Debian 12 sur serveur HP ProLiant",
      "Configuration reseau et services systeme (MariaDB, Apache2)",
      "Deploiement de Zabbix 6.0 (serveur + agents)",
      "Ajout d'hotes Windows dans l'interface Zabbix",
      "Creation de tableaux de bord de supervision",
      "Configuration des alertes (CPU > 90%, espace disque)",
      "Documentation technique de l'installation",
    ],
    images: [
      { src: "/assets/debian-server.JPG", legende: "Serveur HP ProLiant Debian 12 avec interface Zabbix en production" },
      { src: "/assets/zabbix-install.png", legende: "Installation reussie de l'interface Zabbix 6.0" },
      { src: "/assets/zabbix_dashboard.png", legende: "Tableau de bord Zabbix - supervision CPU et espace disque" },
    ],
    documents: [
      { nom: "Documentation Zabbix", fichier: "/assets/Documentation_zabbix.pdf", description: "Guide d'installation et configuration de l'agent Zabbix redige lors du stage" },
    ],
    couleur: "from-blue-600 to-cyan-500",
    logo: "/assets/zabbix.webp",
    icon: "MON",
  },
  {
    id: "infrastructure-reseau",
    titre: "Infrastructure Reseau Mairie de Coignieres",
    courte: "Analyse et schematisation de l'infrastructure reseau de la mairie",
    description: "Analyse complete de l'infrastructure reseau de la Mairie de Coignieres. Realisation de schemas de topologie reseau incluant la segmentation par VLANs et la configuration des points d'acces Wi-Fi.",
    contexte: "Besoin de documenter et cartographier l'infrastructure reseau existante de la mairie.",
    objectif: "Produire une documentation reseau complete et des schemas de topologie a jour.",
    resultat: "Documentation reseau complete avec schemas VLANs et inventaire des equipements actifs.",
    technologies: ["Cisco Packet Tracer", "VLANs", "WPA2-PSK", "Documentation reseau"],
    categorie: "Reseau",
    type: "entreprise",
    missions: [
      "Audit de l'infrastructure reseau existante",
      "Realisation du schema de topologie reseau",
      "Documentation des VLANs (Admin, Guests, Organisation)",
      "Analyse des points d'acces Wi-Fi et niveaux de securite",
      "Identification des equipements actifs (commutateurs, routeurs)",
      "Redaction de la documentation technique",
    ],
    images: [
      { src: "/assets/inframairie.png", legende: "Schema d'infrastructure reseau de la Mairie de Coignieres - VLANs, switches, pare-feu, videosurveillance" },
    ],
    documents: [],
    couleur: "from-emerald-600 to-teal-500",
    icon: "NET",
  },
  {
    id: "gestion-parc",
    titre: "Deploiement OCS Inventory + GLPI + GPO",
    courte: "Solution complete de gestion de parc avec inventaire automatise via GPO",
    description: "Mise en place d'une solution complete de gestion de parc informatique avec GLPI et OCS Inventory. Deploiement automatise des agents OCS via GPO sur les postes Windows du domaine.",
    contexte: "Besoin de centraliser l'inventaire du parc et le suivi des equipements.",
    objectif: "Mettre en place une solution inventaire + gestion de parc et automatiser le deploiement de l'agent sur les postes.",
    resultat: "Inventaire automatise et centralise, parc visible dans GLPI, deploiement agent industrialise via GPO.",
    technologies: ["GLPI", "OCS Inventory", "Windows Server", "GPO", "Active Directory"],
    categorie: "Gestion de parc",
    type: "entreprise",
    missions: [
      "Installation et configuration de GLPI",
      "Deploiement d'OCS Inventory Server",
      "Liaison GLPI - OCS pour synchronisation automatique",
      "Preparation du package agent OCS",
      "Deploiement de l'agent via GPO sur les postes du domaine",
      "Verification de la remontee des machines",
    ],
    images: [],
    documents: [],
    couleur: "from-amber-600 to-yellow-500",
    logo: "/assets/ocsGLPIlogo.png",
    icon: "PAR",
  },
  {
    id: "virtualisation",
    titre: "Mise en place d'un serveur FTPS (FileZilla)",
    courte: "Serveur FTP securise en FTPS pour echanges internes/externes",
    description: "Mise en place d'un serveur FileZilla en mode FTPS (FTP over TLS/SSL) pour le transfert securise de fichiers.",
    contexte: "Besoin de mettre a disposition un partage de fichiers securise pour des echanges internes/externes.",
    objectif: "Deployer un serveur FTP securise en FTPS afin de chiffrer les transferts et renforcer la confidentialite.",
    resultat: "Service operationnel : transferts chiffres, acces controle par comptes et permissions.",
    technologies: ["VirtualBox", "FileZilla Server", "FTPS", "TLS/SSL", "Windows Server"],
    categorie: "Infrastructure",
    type: "entreprise",
    missions: [
      "Installation de FileZilla Server sur VM Windows Server",
      "Activation du FTPS (TLS)",
      "Parametrage reseau (ports / acces)",
      "Tests de connexion securisee",
      "Creation de comptes et droits d'acces",
      "Documentation de la procedure",
    ],
    images: [],
    documents: [
      { nom: "Documentation FileZilla Server", fichier: "/assets/filezilla-documentation.odt", description: "Documentation complete de l'installation et configuration du serveur FTPS" },
    ],
    couleur: "from-sky-600 to-indigo-500",
    logo: "/assets/filezilla.webp",
    icon: "SRV",
  },


  {
    id: "glpi-ocs-m2l",
    titre: "OCS Inventory + GLPI - Gestion de parc M2L",
    courte: "Solution d'inventaire et de ticketing pour la Maison des Ligues (M2L)",
    description: "Mise en place d'une solution complete de gestion de parc informatique (OCS Inventory + GLPI) dans le contexte de la Maison des Ligues (M2L). Le serveur a ete deploye sur une VM Ubuntu via Proxmox avec une pile LAMP. L'agent OCS installe sur les postes clients permet la remontee automatique des informations dans GLPI.",
    contexte: "La Maison des Ligues (M2L) avait besoin d'une solution de gestion centralisee de son parc informatique.",
    objectif: "Mettre en place un inventaire automatique des postes, centraliser les informations du parc et faciliter la gestion des equipements.",
    resultat: "Serveur OCS Inventory et GLPI fonctionnel, inventaire automatise du poste client, integration des donnees dans GLPI, creation d'utilisateurs.",
    technologies: ["Proxmox", "Ubuntu", "Apache2", "MySQL", "PHP", "OCS Inventory", "GLPI"],
    categorie: "Gestion de parc",
    type: "scolaire",
    numero: "RP2",
    periode: "Fevrier 2026 - Avril 2026",
    lieu: "H3 Campus - Poissy",
    missions: [
      "Installation du serveur Ubuntu sur Proxmox",
      "Mise en place de la pile LAMP (Apache, MySQL, PHP)",
      "Installation et configuration d'OCS Inventory Server",
      "Installation et configuration de GLPI",
      "Configuration du plugin OCS dans GLPI",
      "Installation de l'agent OCS sur un poste client",
      "Mise en place de la synchronisation OCS vers GLPI",
      "Tests de remontee des informations et validation",
      "Creation d'utilisateurs et droits d'acces",
    ],
    images: [],
    documents: [
      { nom: "Fiche descriptive RP2 - GLPI", fichier: "/assets/Fiche-descriptive-de-realisation-professionnelle-GLPI__7_.pdf", description: "Fiche officielle BTS SIO E6 - Administration des systèmes et réseaux" },
    ],
    ficheWord: "/assets/Fiche-descriptive-de-realisation-professionnelle-GLPI.docx",
    lienProduction: "https://bit.ly/4sfn9yF",
    couleur: "from-amber-600 to-orange-500",
    logo: "/assets/ocsGLPIlogo.png",
    icon: "PAR",
  },
  {
    id: "nagios-m2l",
    titre: "Nagios - Supervision reseau M2L",
    courte: "Mise en place de Nagios4 pour la supervision de l'infrastructure de la M2L",
    description: "Installation et configuration de Nagios4 pour superviser les equipements reseau et services critiques de la Maison des Ligues (M2L). La solution permet de surveiller en temps reel l'etat des hotes, des services (HTTP, SSH, ping) et d'envoyer des alertes par mail en cas de defaillance.",
    contexte: "Aucun outil de supervision n'etait en place a la M2L, rendant difficile l'identification des pannes et defaillances reseau.",
    objectif: "Deployer Nagios4 pour assurer une surveillance continue des equipements, creer des notifications et gerer les seuils d'alerte.",
    resultat: "Supervision de la baie operationnelle, notifications par mail configurees, seuils critiques et warnings definis, interface web Nagios accessible.",
    technologies: ["Proxmox", "Ubuntu", "Nagios Core", "Apache", "Nagios Plugins", "Postfix", "SSH", "SNMP"],
    categorie: "Supervision",
    type: "scolaire",
    numero: "RP2",
    periode: "Decembre 2025 - Mars 2026",
    lieu: "H3 Campus",
    missions: [
      "Installation de Nagios4 sur serveur Ubuntu (VM Proxmox)",
      "Configuration des hotes (hosts) a superviser",
      "Configuration des services (ping, HTTP, SSH, CPU)",
      "Mise en place des notifications par mail (Postfix)",
      "Definition des seuils critiques et warnings",
      "Configuration SNMP sur les equipements reseau",
      "Tests : verification remontee etats UP/DOWN",
      "Simulation de panne pour validation des alertes",
      "Verification reception notifications par mail",
    ],
    images: [],
    documents: [
      { nom: "Fiche descriptive RP2 - Nagios", fichier: "/assets/Fiche-descriptive-de-realisation-professionnelle-NAGIOS__6_.pdf", description: "Fiche officielle BTS SIO E6 - Administration des systèmes et réseaux" },
    ],
    ficheWord: "/assets/Fiche-descriptive-de-realisation-professionnelle-NAGIOS.docx",
    lienProduction: "https://bit.ly/4sfn9yF",
    couleur: "from-slate-700 to-slate-900",
    logo: "/assets/logo-nagios.png",
    icon: "MON",
  },
  {
    id: "support-technique",
    titre: "Interventions sur sites-CCAS/MDJ/écoles",
    courte: "Interventions reseau, installation borne Wi-Fi et tests de connexion sur sites",
    description: "Dans le cadre de mon stage a la Mairie de Coignieres, j'ai effectue plusieurs interventions sur differents sites (ecoles maternelles, ecoles primaires, CCAS). Mise en place d'une borne Wi-Fi TP-Link au CCAS, realisation de tests de connexion RJ45 avec un wiretracker, et resolution de problemes d'antivirus Trend Micro sur les postes.",
    contexte: "Les differents sites de la mairie (ecoles, CCAS, MDJ) avaient des problemes de connectivite reseau et des postes infectes necessitant une reinstallation de l'antivirus.",
    objectif: "Assurer la connectivite reseau sur les sites, installer une borne Wi-Fi au CCAS et remedier aux problemes d'antivirus Trend Micro.",
    resultat: "Borne Wi-Fi TP-Link operationnelle au CCAS, connectivite reseau validee dans les ecoles, antivirus Trend Micro reinstalle sur tous les postes concernes.",
    technologies: ["TP-Link", "Wi-Fi", "RJ45", "Trend Micro", "Wiretracker"],
    categorie: "Support",
    type: "entreprise",
    missions: [
      "Installation et configuration borne Wi-Fi TP-Link au CCAS",
      "Tests de connexion RJ45 avec wiretracker dans les ecoles maternelles et primaires",
      "Diagnostic et resolution de problemes de connectivite reseau",
      "Desinstallation et reinstallation de l'antivirus Trend Micro sur tous les postes",
      "Deplacement sur les differents sites de la mairie (ecoles, CCAS, MDJ)",
      "Rapport d'intervention et documentation des problemes resolus",
    ],
    images: [
      { src: "/assets/wiretracker.jpeg", legende: "Wiretracker - Outil de test de cables RJ45 utilise dans les ecoles" },
      { src: "/assets/borne-ccas.JPG", legende: "Borne Wi-Fi TP-Link installee au CCAS de Coignieres" },
    ],
    documents: [],
    couleur: "from-orange-600 to-red-500",
    icon: "SRV",
  },
  {
    id: "ap2-m2l",
    titre: "AP2 - Projets DYLAN & ASSIZ (Maison des Ligues)",
    courte: "Insertion dynamique VLAN et infrastructure Wi-Fi temporaire pour la M2L",
    description: "Atelier de Professionnalisation N2 realise en groupe (Ali H., Sasha H., Mehdi A.) dans le contexte de la Maison des Ligues (M2L). Deux missions : le projet DYLAN (insertion dynamique des PC portables dans le bon VLAN via MAC-based VLAN) et le projet ASSIZ (infrastructure Wi-Fi temporaire securisee pour les VIemes assises nationales de l'Escrime).",
    contexte: "La Maison des Ligues heberge plusieurs organisations sportives partageant un reseau commun.",
    objectif: "Mission 1 : insertion dynamique des PC dans le bon VLAN. Mission 2 : infrastructure Wi-Fi temporaire securisee.",
    resultat: "Solution MAC-based VLAN retenue pour DYLAN. Infrastructure Wi-Fi a 3 points d'acces segmentes retenue pour ASSIZ.",
    technologies: ["Cisco Packet Tracer", "MAC-based VLAN", "802.1Q", "Wi-Fi", "WPA2-PSK", "SSID", "Switch Cisco"],
    categorie: "Reseau",
    type: "scolaire",
    missions: [
      "Analyse du contexte de la Maison des Ligues",
      "Etude et comparaison de 3 solutions VLAN (Port-based, Protocol-based, MAC-based)",
      "Choix et justification de la solution MAC-based VLAN pour DYLAN",
      "Conception de l'infrastructure Wi-Fi temporaire pour ASSIZ",
      "Etude de 2 solutions Wi-Fi (SSID multiples vs Controleur + VLANs)",
      "Maquettage sur Cisco Packet Tracer",
      "Redaction du dossier AP2 et presentation PowerPoint",
    ],
    images: [
      { src: "/assets/dylan.png", legende: "Projet DYLAN - Topologie reseau MAC-based VLAN sur Cisco Packet Tracer" },
      { src: "/assets/assiz.png", legende: "Projet ASSIZ - Infrastructure Wi-Fi temporaire avec segmentation VLANs" },
    ],
    documents: [
      { nom: "Dossier AP2 - Rapport complet", fichier: "/assets/AP2_M2L.docx", description: "Rapport Word complet : contexte, solutions, comparaison, annexes" },
      { nom: "Presentation AP2 - PowerPoint", fichier: "/assets/AP2_presentation.pptx", description: "Support de presentation du projet devant le jury" },
    ],
    couleur: "from-blue-600 to-indigo-500",
    icon: "ENT",
  },
  {
    id: "projet-dylan",
    titre: "Projet DYLAN - Insertion dynamique VLAN",
    courte: "Insertion dynamique des PC portables dans leur VLAN a la Maison des Ligues",
    description: "Ce projet vise a permettre l'insertion dynamique des PC portables dans le VLAN correspondant a leur structure lorsqu'ils sont connectes a une prise Ethernet commune dans les salles de reunion de la Maison des Ligues (M2L).",
    contexte: "La Maison des Ligues accueille plusieurs structures qui partagent des prises reseau communes.",
    objectif: "Configurer une infrastructure reseau permettant l'insertion dynamique des equipements dans le bon VLAN.",
    resultat: "Infrastructure reseau fonctionnelle avec affectation automatique des VLANs par structure.",
    technologies: ["Cisco Packet Tracer", "VLANs", "802.1Q", "Switches Cisco"],
    categorie: "Reseau",
    type: "scolaire",
    missions: [
      "Analyse du besoin et de l'infrastructure existante",
      "Conception de la topologie reseau avec VLANs",
      "Configuration des switches Cisco",
      "Mise en place du 802.1Q (trunk)",
      "Tests de connectivite entre VLANs",
      "Documentation et schema reseau",
    ],
    images: [
      { src: "/assets/dylan.png", legende: "Schema reseau du projet DYLAN - topologie Cisco Packet Tracer" },
    ],
    documents: [],
    couleur: "from-blue-600 to-indigo-500",
    icon: "VLN",
  },
  {
    id: "inventaire-proxmox",
    titre: "Inventaire du matériel informatique et mise en place d'une infrastructure de virtualisation avec Proxmox",
    courte: "Inventaire complet du parc M2L et déploiement d'une infrastructure Proxmox",
    description: "Avant de déployer GLPI et Nagios sur le réseau de la M2L, notre équipe a réalisé un inventaire complet du matériel informatique existant : routeurs Cisco, commutateurs, points d'accès WiFi, serveurs et postes clients. Cet inventaire a servi de base pour la mise en place d'une infrastructure de virtualisation avec Proxmox.",
    contexte: "Projet scolaire AP2 — IPSSI SQY, réalisé en équipe avant le déploiement GLPI/OCS et Nagios sur le réseau de la M2L.",
    objectif: "Recenser et documenter l'ensemble du matériel informatique de la M2L, puis mettre en place une infrastructure de virtualisation Proxmox pour héberger les services.",
    resultat: "Inventaire complet documenté par catégorie de matériel. Infrastructure Proxmox opérationnelle servant de base aux projets GLPI et Nagios.",
    technologies: ["Proxmox", "VirtualBox", "Cisco", "Windows Server", "Linux", "Excel"],
    categorie: "Réseau",
    type: "scolaire",
    numero: "AP2",
    periode: "Février 2026 - Mars 2026",
    lieu: "IPSSI SQY",
    missions: [
      "Inventaire des routeurs Cisco du réseau M2L",
      "Inventaire des commutateurs Cisco",
      "Inventaire des points d'accès WiFi Cisco",
      "Inventaire des serveurs et postes clients",
      "Mise en place de l'infrastructure de virtualisation Proxmox",
      "Documentation complète du parc informatique",
    ],
    images: [],
    documents: [
      { nom: "Inventaire Routeurs Cisco", fichier: "/assets/Routeur_Cisco_Inventaire.docx", description: "Inventaire détaillé des routeurs Cisco du réseau M2L" },
      { nom: "Inventaire Commutateurs Cisco", fichier: "/assets/Commutateur_Cisco_Inventaire.docx", description: "Inventaire des commutateurs Cisco" },
      { nom: "Inventaire Points d'accès WiFi", fichier: "/assets/AP_WiFi_Cisco_Inventaire.docx", description: "Inventaire des bornes WiFi Cisco" },
      { nom: "Inventaire Serveurs", fichier: "/assets/PC_Serveur_Inventaire.docx", description: "Inventaire des serveurs du parc M2L" },
      { nom: "Inventaire Postes Clients", fichier: "/assets/PC_Client_Inventaire.docx", description: "Inventaire des postes clients" },
      { nom: "Projet Équipe 4", fichier: "/assets/Equipe-4_PROJET.xlsx", description: "Fichier de projet complet de l'équipe 4" },
    ],
    couleur: "from-orange-600 to-amber-500",
    icon: "INV",
  },
  {
    id: "projet-assiz",
    titre: "Projet ASSIZ - Infrastructure Wi-Fi Escrime",
    courte: "Infrastructure Wi-Fi temporaire securisee pour les VIemes assises nationales de l'Escrime",
    description: "Projet visant a concevoir et deployer une infrastructure Wi-Fi temporaire pour les VIemes assises nationales de l'Escrime. La mission : creer un reseau Wi-Fi temporaire bien securise, avec des acces separes pour les invites et le staff.",
    contexte: "Les assises nationales de l'Escrime necessitent un reseau Wi-Fi temporaire securise avec separation des acces.",
    objectif: "Deployer une infrastructure Wi-Fi temporaire avec segmentation invites/staff et securisation des acces.",
    resultat: "Infrastructure Wi-Fi operationnelle avec VLANs separes et WPA2-PSK pour le staff.",
    technologies: ["Wi-Fi", "VLANs", "WPA2-PSK", "Cisco Packet Tracer", "Points d'acces"],
    categorie: "Reseau",
    type: "scolaire",
    missions: [
      "Analyse des besoins en connectivite",
      "Conception de l'architecture Wi-Fi temporaire",
      "Configuration des points d'acces (SSID staff / invites)",
      "Segmentation reseau avec VLANs",
      "Securisation WPA2-PSK pour le staff",
      "Tests et validation de l'infrastructure",
    ],
    images: [
      { src: "/assets/assiz.png", legende: "Schema reseau Wi-Fi temporaire - Projet ASSIZ" },
    ],
    documents: [],
    couleur: "from-emerald-600 to-green-500",
    icon: "WIF",
  },
  {
    id: "cybersecurite-linux",
    titre: "Cybersecurite & Linux",
    courte: "Etude du 2FA, VM Kali Linux et acces SSH securise",
    description: "Etude des mecanismes d'authentification a deux facteurs (2FA) et de leurs vulnerabilites, configuration d'une machine virtuelle Kali Linux pour des tests de penetration, et mise en place d'un acces SSH securise avec cles asymetriques.",
    contexte: "TP de securite informatique a l'IPSSI - comprendre les attaques et les defenses.",
    objectif: "Comprendre le contournement du 2FA et securiser un acces distant via SSH.",
    resultat: "Maitrise des techniques d'attaque 2FA et d'un acces SSH securise par cles RSA.",
    technologies: ["Kali Linux", "SSH", "VirtualBox", "2FA", "RSA"],
    categorie: "Securite",
    type: "scolaire",
    missions: [
      "Configuration d'une VM Kali Linux sous VirtualBox",
      "Etude du contournement de l'authentification 2FA",
      "Mise en place d'un acces SSH avec cles RSA",
      "Tests de securite en environnement isole",
      "Analyse des vulnerabilites d'authentification",
      "Redaction d'un rapport de securite",
    ],
    images: [
      { src: "/assets/hacked.png", legende: "Environnement de test cybersecurite" },
    ],
    documents: [
      { nom: "TP Challenge - Attaque MITM ARP Spoofing avec Ettercap", fichier: "/assets/TP Challenge Réaliser une attaque MITM ARP Spoofing avec Ettercap.pdf", description: "TP complet sur la realisation d'une attaque Man-in-the-Middle par ARP Spoofing" },
    ],
    couleur: "from-red-600 to-orange-500",
    icon: "SEC",
  },
  {
    id: "site-web",
    titre: "AP1 - Projet NEBULAX-SOCCER (e-Commerce Esport)",
    courte: "AP1 IPSSI - Boutique e-commerce de produits derives pour une equipe esport",
    description: "Dans le cadre du projet AP1 a l'IPSSI, creation d'une entreprise fictive NEBULAX, une boutique e-commerce specialisee dans les produits derives d'une equipe esport (maillots, t-shirts, casquettes, goodies...). Slogan : 'Les vainqueurs l'ecrivent, les vaincus racontent l'histoire'. Conception de la charte graphique, creation du site vitrine HTML/CSS/JS et redaction du business plan.",
    contexte: "Projet AP1 IPSSI - creation d'une entreprise fictive NEBULAX avec presence web. L'entreprise propose des produits derives esport pour generer des revenus et fideliser une communaute passionnee.",
    objectif: "Creer une boutique e-commerce complete avec charte graphique professionnelle, site web et business plan pour l'entreprise NEBULAX.",
    resultat: "Site web operationnel avec design coherent, charte graphique complete, business plan redige et presentation PowerPoint realisee.",
    technologies: ["HTML", "CSS", "JavaScript", "Figma", "Canva"],
    categorie: "Developpement",
    type: "scolaire",
    missions: [
      "Creation de l'entreprise fictive NEBULAX (SARL e-commerce esport)",
      "Conception de la charte graphique et du logo",
      "Developpement du site vitrine HTML/CSS/JS",
      "Redaction du business plan (analyse de marche, plan de croissance)",
      "Creation des fiches de poste (comptable, commercial, designer)",
      "Preparation de la presentation PowerPoint",
      "Analyse concurrentielle (Fnatic, G2, Vitality, Karmine Corp...)",
    ],
    images: [
      { src: "/assets/maillot1.jpg", legende: "Maillot NEBULAX - Collection principale" },
      { src: "/assets/maillot2.jpg", legende: "Maillot NEBULAX - Variante" },
      { src: "/assets/maillot3.jpg", legende: "Produits derives NEBULAX" },
      { src: "/assets/maillot4.jpg", legende: "Produits derives NEBULAX" },
      { src: "/assets/maillot5.jpg", legende: "Produits derives NEBULAX" },
      { src: "/assets/maillot6.jpg", legende: "Produits derives NEBULAX" },
      { src: "/assets/FooT.webp", legende: "Slogan NEBULAX - Les vainqueurs l'écrivent, les vaincus racontent l'histoire" },
    ],
    documents: [
      {
        nom: "Présentation NEBULAX - PowerPoint",
        fichier: "/assets/AP1nebulax-soccer.pptx",
        description: "Présentation officielle du projet AP1 - Business plan et stratégie NEBULAX"
      },
      {
        nom: "Devis client",
        fichier: "/assets/devis_client_ap1.docx",
        description: "Devis établi pour un client dans le cadre du projet AP1"
      },
      {
        nom: "Bon de commande client",
        fichier: "/assets/bon_commande_client_ap1.docx",
        description: "Bon de commande client AP1"
      },
      {
        nom: "Facture client",
        fichier: "/assets/facture_client_ap1.docx",
        description: "Facture client établie dans le cadre du projet AP1"
      },
      {
        nom: "Plan d'affaires - Flock Soccer",
        fichier: "/assets/Plans Flock soccer.odt",
        description: "Plan d'affaires complet de l'entreprise virtuelle AP1"
      },
    ],
    couleur: "from-violet-600 to-purple-500",
    icon: "WEB",
  },
  {
    id: "e6-glpi-ocs",
    titre: "E6 - Solution OCS Inventory + GLPI pour la M2L",
    courte: "Gestion de parc informatique avec inventaire automatise via OCS et GLPI sur Proxmox",
    description: "Realisation professionnelle E6 (RP2) realisee dans le contexte de la Maison des Ligues (M2L). Mise en place d'une solution complete de gestion de parc informatique avec OCS Inventory et GLPI sur une infrastructure virtualisee Proxmox/Ubuntu. Objectif : centraliser l'inventaire automatique des postes et faciliter la gestion des equipements.",
    contexte: "La M2L avait besoin d'une solution de gestion centralisee du parc informatique pour automatiser l'inventaire des postes.",
    objectif: "Mettre en place un inventaire automatique des postes, centraliser les informations du parc et faciliter la gestion des equipements.",
    resultat: "Serveur OCS Inventory et GLPI fonctionnels, inventaire automatise du poste client, integration des donnees dans GLPI, creation d'utilisateurs.",
    technologies: ["Proxmox", "Ubuntu", "Apache2", "MySQL", "PHP", "OCS Inventory", "GLPI", "LAMP"],
    categorie: "Gestion de parc",
    type: "scolaire",
    missions: [
      "Installation du serveur Ubuntu sur Proxmox (pve1)",
      "Mise en place de la pile LAMP (Apache, MySQL, PHP)",
      "Installation et configuration OCS Inventory Server",
      "Installation et configuration GLPI",
      "Configuration du plugin OCS dans GLPI",
      "Installation de l'agent OCS sur poste client",
      "Mise en place de la synchronisation OCS vers GLPI",
      "Tests de remontee d'inventaire et validation",
    ],
    images: [],
    documents: [
      { nom: "Fiche descriptive E6 - GLPI + OCS", fichier: "/assets/fiche-glpi.docx", description: "Fiche officielle de realisation professionnelle BTS SIO E6" },
    ],
    couleur: "from-amber-600 to-yellow-500",
    icon: "PAR",
  },
  {
    id: "e6-nagios",
    titre: "E6 - Supervision reseau avec Nagios4 pour la M2L",
    courte: "Mise en place de Nagios4 pour la supervision de la baie reseau de la M2L",
    description: "Realisation professionnelle E6 (RP2) realisee dans le contexte de la Maison des Ligues (M2L). Mise en place de Nagios4 sur Ubuntu/Proxmox pour superviser les equipements reseau et services critiques de la baie. Aucun outil de supervision n'etait en place avant ce projet.",
    contexte: "Les serveurs et equipements de la M2L necessitaient une surveillance continue pour detecter rapidement les incidents. Aucun outil de supervision n'etait en place.",
    objectif: "Mettre en place une solution de supervision Nagios4 pour surveiller les equipements reseau et envoyer des alertes en cas de probleme.",
    resultat: "Supervision operationnelle de la baie, notifications mail configurees, seuils critiques et warnings definis, interface web Nagios accessible.",
    technologies: ["Proxmox", "Ubuntu", "Nagios Core", "Apache", "SNMP", "Postfix", "SSH"],
    categorie: "Supervision",
    type: "scolaire",
    missions: [
      "Installation de Nagios4 sur serveur Ubuntu (Proxmox)",
      "Configuration des hotes (hosts) a superviser",
      "Configuration des services (ping, HTTP, SSH, CPU)",
      "Mise en place des notifications par mail (Postfix)",
      "Definition des seuils critiques et warnings",
      "Tests de remontee d'etat (UP/DOWN)",
      "Simulation de panne pour validation des alertes",
      "Verification de l'interface web Nagios",
    ],
    images: [],
    documents: [
      { nom: "Fiche descriptive E6 - Nagios", fichier: "/assets/fiche-nagios.docx", description: "Fiche officielle de realisation professionnelle BTS SIO E6" },
    ],
    couleur: "from-sky-600 to-cyan-500",
    icon: "MON",
  },
  {
    id: "vlan-ccna",
    titre: "Mise en place et configuration de réseaux VLAN (CCNA-2-1)",
    courte: "Segmentation logique d'un LAN en domaines de diffusion avec VLANs sur Cisco Packet Tracer",
    description: "TP Cisco Networking Academy : découverte du fonctionnement des VLANs. Observation du trafic de diffusion avec et sans VLAN sur une infrastructure composée de 3 commutateurs (S1, S2, S3) et 9 PC répartis en VLAN10, VLAN20 et VLAN30.",
    contexte: "Projet scolaire CCNA-2-1 réalisé à H3 Campus dans le cadre du BTS SIO SISR.",
    objectif: "Comprendre la segmentation réseau par VLANs et observer l'isolation du trafic de diffusion entre domaines.",
    resultat: "Infrastructure VLAN opérationnelle : isolation du trafic de diffusion validée, ping inter-VLAN bloqués, ping intra-VLAN fonctionnels.",
    technologies: ["Cisco Packet Tracer", "VLANs", "802.1Q", "Switches Cisco", "TCP/IP"],
    categorie: "Réseau",
    type: "scolaire",
    periode: "Novembre 2025 - Décembre 2025",
    lieu: "H3 Campus",
    missions: [
      "Configuration des VLANs 10, 20 et 30 sur 3 commutateurs Cisco",
      "Affectation des ports aux VLANs correspondants",
      "Observation du trafic ARP et ping en mode simulation",
      "Vérification de l'isolation des domaines de diffusion",
      "Test de connectivité intra-VLAN (PC1 → PC4, même VLAN10)",
      "Test d'isolation inter-VLAN (PC1 → PC6, VLAN10 → VLAN30)",
      "Suppression des VLANs et observation du comportement sans segmentation",
    ],
    images: [],
    documents: [
      { nom: "TP Découverte VLAN - CCNA", fichier: "/assets/tp_decouverte_vlan_MEHDI_AHMIDDOUCH.pdf", description: "TP complet Cisco Networking Academy - Découverte du fonctionnement des VLANs" },
    ],
    couleur: "from-emerald-600 to-teal-500",
    icon: "NET",
  },
];

export const VEILLE = [
  {
    titre: "Négociateurs américains de ransomwares condamnés à 4 ans de prison pour les attaques BlackCat",
    date: "1er Mai 2026",
    resume: "Trois négociateurs américains spécialisés dans les attaques du groupe BlackCat (ALPHV) ont plaidé coupable d'extorsion et ont été condamnés à 4 ans de prison. Une décision judiciaire marquante dans la lutte contre les ransomwares.",
    analysePerso: "Cet article vient confirmer ce que le premier article sur BlackCat avait introduit : le ransomware est aujourd'hui une véritable industrie criminelle organisée avec des rôles bien définis, développeurs, affiliés et négociateurs. Le fait que des négociateurs soient poursuivis séparément montre que la justice commence à démanteler ces organisations couche par couche. Pour moi c'est important car ça illustre concrètement le modèle RaaS que je suis via mes alertes Google, et ça montre que la réponse judiciaire commence à s'adapter à la complexité de ces structures.",
    source: "NetCost Security",
    image: "https://www.netcost-security.fr/wp-content/uploads/2026/05/Negociateurs-americains-de-ransomwares-condamnes-a-4-ans-de-prison-1152x648.jpg",
    lien: "https://www.netcost-security.fr/actualites/272709/negociateurs-americains-de-ransomwares-condamnes-a-4-ans-de-prison-pour-les-attaques-blackcat/",
    projetId: "cybersecurite-linux",
  },
  {
    titre: "Hackers de centaines de milliers de comptes Roblox : voici ce qu'il faut faire",
    date: "30 Avril 2026",
    resume: "Des hackers ont compromis des centaines de milliers de comptes Roblox. Malwarebytes détaille les méthodes utilisées et les mesures à prendre pour sécuriser son compte face à ce type d'attaque de masse.",
    analysePerso: "Cet article illustre une technique d'attaque classique mais toujours efficace : le malware déguisé en outil légitime. Le fait que 610 000 comptes aient été compromis montre l'ampleur que peut prendre une campagne ciblant des utilisateurs peu méfiants, souvent jeunes. En tant que futur administrateur systèmes, ça me rappelle l'importance de la sensibilisation des utilisateurs et du contrôle des logiciels installés sur un parc.",
    source: "Malwarebytes",
    image: "https://www.malwarebytes.com/wp-content/uploads/sites/2/2025/02/Roblox.png?w=600",
    lien: "https://www.malwarebytes.com/fr/blog/news/2026/04/hackers-stole-hundreds-of-thousands-of-roblox-accounts-heres-what-to-do",
    projetId: "cybersecurite-linux",
  },
  {
    titre: "Le ransomware VECT 2.0 altéré agit comme un effaceur de données pour les gros fichiers",
    date: "28 Avril 2026 — 23h35",
    resume: "Une variante du ransomware VECT 2.0 a été découverte : au lieu de chiffrer les gros fichiers, il les détruit définitivement. Un comportement hybride entre ransomware et wiper qui complique la récupération des données.",
    analysePerso: "Ce qui m'a frappé dans cet article c'est l'évolution du ransomware vers un comportement destructeur. Traditionnellement un ransomware chiffre les données pour demander une rançon, mais ici VECT 2.0 détruit carrément les gros fichiers sans possibilité de récupération. Ça change tout : même payer la rançon ne servirait à rien. Pour un administrateur systèmes, ça renforce l'importance d'avoir des sauvegardes isolées et régulières, ce que j'ai justement mis en pratique lors de mon alternance chez ATERMES.",
    source: "NetCost Security",
    image: "https://www.netcost-security.fr/wp-content/uploads/2026/04/Le-ransomware-VECT-20-altere-agit-comme-un-effaceur-de-1152x648.jpg",
    lien: "https://www.netcost-security.fr/actualites/272634/le-ransomware-vect-2-0-altere-agit-comme-un-effaceur-de-donnees-pour-les-gros-fichiers/",
    projetId: "cybersecurite-linux",
  },
  {
    titre: "VECT 2.0 : Ransomware ou Wiper ?",
    date: "28 Avril 2026",
    resume: "LeMagIT analyse le cas VECT 2.0, un malware à double comportement : ransomware classique pour les petits fichiers, wiper destructeur pour les gros. Une évolution inquiétante des menaces cyber en 2026.",
    analysePerso: "Cet article complète parfaitement le précédent. VECT 2.0 ne rentre plus dans la case classique du ransomware : il mélange chiffrement et destruction, ce qui le rapproche d'un wiper. Ce qui est inquiétant c'est que les victimes ne peuvent plus compter sur le paiement de la rançon pour récupérer leurs données. Pour moi, ça illustre un vrai changement de stratégie des cybercriminels qui passent d'une logique d'extorsion financière à une logique de destruction pure. En tant que futur administrateur, ça confirme que la sauvegarde isolée n'est plus une option mais une nécessité absolue.",
    source: "LeMagIT",
    image: "https://www.lemagit.fr/visuals/ComputerWeekly/HeroImages/social-media-content-moderation-delete-data-freshidea-adobe.jpg",
    lien: "https://www.lemagit.fr/actualites/366642339/VECT-20-Ransomware-ou-Wiper",
    projetId: "cybersecurite-linux",
  },
  {
    titre: "BlackCat : trois négociateurs cyber plaident coupable d'extorsion",
    date: "27 Avril 2026",
    resume: "Trois individus ayant négocié des rançons pour le groupe BlackCat ont reconnu leur culpabilité devant la justice. Cette affaire illustre la montée en puissance des poursuites judiciaires contre les acteurs du cybercrime.",
    analysePerso: "Cet article m'a marqué car il montre que la justice ne cible plus seulement les développeurs de ransomware, mais toute la chaîne : y compris les négociateurs. Le groupe BlackCat (ALPHV) est l'un des plus actifs en RaaS, un sujet que je suis de près via mes alertes. Cette condamnation prouve que le modèle RaaS n'est plus aussi protégé qu'il y paraît.",
    source: "DCOD",
    image: "https://dcod.ch/wp-content/uploads/2026/04/DCOD-BlackCat-trois-negociateurs-cyber-plaident-coupable-dextorsion.png",
    lien: "https://dcod.ch/2026/04/27/blackcat-trois-negociateurs-coupables/",
    projetId: "cybersecurite-linux",
  },
];
